# -*- coding: utf-8 -*-
# 《できる日本語 初中級 本冊【第2版】》三語語彙表（英語/中国語/ネパール語 原文照译）
# 数据来源：E:\教科書\できる日本語＆漢字たまご\初中級\語彙リスト 三份PDF
chuukyuu_words = {
1: [
 {"kanji":"それでは","kana":"それでは","eng":"well, then (at beginning of a sentence)","cn":"那么、那就","ne":"त्यसोभए"},
 {"kanji":"自己紹介","kana":"じこしょうかい","eng":"self-introduction","cn":"自我介绍","ne":"आफ्नो परिचय"},
 {"kanji":"～と申します","kana":"～ともうします","eng":"“My name is ～.” (humble language)","cn":"我叫……","ne":"(आफू) लाई भनिन्छ"},
 {"kanji":"では","kana":"では","eng":"in that case, if so","cn":"那么","ne":"त्यसोभए/अब"},
 {"kanji":"いらっしゃいます","kana":"いらっしゃいます","eng":"go, come (respectful language referring to someone else)","cn":"来","ne":"(अरू) हुनुहुन्छ"},
 {"kanji":"方","kana":"かた","eng":"person (respectful language referring to someone else)","cn":"人（尊称）","ne":"(अरू) व्यक्ति"},
 {"kanji":"参りました","kana":"まいりました","eng":"go, come (humble language referring to oneself; past form of 参ります)","cn":"来了","ne":"(आफू) आइपुगेँ"},
 {"kanji":"者","kana":"もの","eng":"person (humble language referring to oneself)","cn":"人（谦称）","ne":"(आफू) व्यक्ति"},
 {"kanji":"（お）刺身","kana":"さしみ","eng":"sashimi (thinly sliced, raw seafood)","cn":"生鱼片","ne":"काँचो माछाको टुक्रा"},
 {"kanji":"チラシ","kana":"","eng":"leaflet, flyer","cn":"广告单","ne":"पर्चा"},
 {"kanji":"お先に失礼します","kana":"おさきにしつれいします","eng":"“Excuse me for going ahead of you”","cn":"对不起，我先走了","ne":"म अगाडि जान्छु"},
 {"kanji":"問い合わせ","kana":"といあわせ","eng":"inquiry","cn":"咨询、问询","ne":"सोधपुछ"},
 {"kanji":"こちらへどうぞ","kana":"こちらへどうぞ","eng":"“Please come this way”","cn":"这边请","ne":"यहाँ आउनुहोला"},
 {"kanji":"日常会話","kana":"にちじょうかいわ","eng":"daily conversation","cn":"日常会话","ne":"दैनिक कुराकानी"},
 {"kanji":"失礼します","kana":"しつれいします","eng":"“Excuse me”","cn":"失礼了","ne":"माफ गर्नुहोला"},
 {"kanji":"半年","kana":"はんとし","eng":"half-year","cn":"半年","ne":"६ महिना"},
 {"kanji":"少々お待ちください","kana":"しょうしょうおまちください","eng":"“Please wait a moment”","cn":"请您稍等","ne":"केही छिन पर्खनुहोला"},
 {"kanji":"ホームページ","kana":"","eng":"website","cn":"网页","ne":"वेब साइट"},
 {"kanji":"よろしくお願いいたします","kana":"よろしくおねがいいたします","eng":"“I am looking forward to knowing you”","cn":"请多多关照","ne":"योरोसिकु ओनेगाइसिमास (एक-आपसमा परिचय गर्दा भनिने)"},
 {"kanji":"面接","kana":"めんせつ","eng":"interview","cn":"面试","ne":"अन्तरवार्ता"},
 {"kanji":"履歴書","kana":"りれきしょ","eng":"resume, CV","cn":"简历","ne":"बायोडाटा"},
 {"kanji":"思い出す","kana":"おもいだす","eng":"remember, recall","cn":"想起","ne":"याद आउनु"},
 {"kanji":"意見","kana":"いけん","eng":"opinion","cn":"意见、见解","ne":"विचार"},
 {"kanji":"希望・する","kana":"きぼう・する","eng":"desire","cn":"希望","ne":"चाहाना गर्नु"},
 {"kanji":"お年寄り","kana":"おとしより","eng":"elderly person","cn":"年长者","ne":"पौढ"},
 {"kanji":"募集・する","kana":"ぼしゅう・する","eng":"recruit, put out a call for","cn":"招聘","ne":"आवेदन फारम खुल्नु"},
 {"kanji":"楽器","kana":"がっき","eng":"musical instrument","cn":"乐器","ne":"बाजागाजा"},
 {"kanji":"言葉","kana":"ことば","eng":"words, language","cn":"词语、语言","ne":"शब्द वा भाषा"},
 {"kanji":"入力・する","kana":"にゅうりょく・する","eng":"input","cn":"输入","ne":"मेशिनमा नाम आदि उल्लेख गर्नु"},
 {"kanji":"自分","kana":"じぶん","eng":"oneself","cn":"自己","ne":"आफू"},
 {"kanji":"出身","kana":"しゅっしん","eng":"hometown, home country","cn":"出生于……","ne":"बाट आउनुभएको"},
 {"kanji":"建物","kana":"たてもの","eng":"building","cn":"建筑物","ne":"बिल्डिङ/भवन"},
 {"kanji":"話","kana":"はなし","eng":"conversation","cn":"话、讲话","ne":"कुराकानी"},
 {"kanji":"野外ライブ","kana":"やがいライブ","eng":"live outdoor concert","cn":"户外演唱会","ne":"खुला चौरको लाइभ इभेन्ट"},
 {"kanji":"歴史","kana":"れきし","eng":"history","cn":"历史","ne":"इतिहास"},
 {"kanji":"～個","kana":"～こ","eng":"things (counter word)","cn":"……个","ne":"～वटा"},
 {"kanji":"～地（例：観光地）","kana":"～ち（れい：かんこうち）","eng":"place, spot (example: sightseeing spot)","cn":"……地方、地点（例：旅游景点）","ne":"～स्थल (जस्तै: पर्यटन स्थल)"},
 {"kanji":"聞き取る","kana":"ききとる","eng":"hear and understand","cn":"听懂","ne":"सुनेर बुझ्न सक्छे"},
 {"kanji":"覚える","kana":"おぼえる","eng":"remember, memorize","cn":"记住、学会","ne":"सम्झनु"},
 {"kanji":"応援・する","kana":"おうえん・する","eng":"encourage, cheer on","cn":"声援、助威","ne":"सघाउनु/हौसला दिनु"},
 {"kanji":"サイクリング・する","kana":"","eng":"do cycling","cn":"骑车兜风","ne":"साइक्लिङ गर्नु"},
 {"kanji":"遅い","kana":"おそい","eng":"slow","cn":"慢","ne":"ढिला"},
 {"kanji":"速い","kana":"はやい","eng":"fast","cn":"快","ne":"चाडोछिटो"},
 {"kanji":"つまらない","kana":"つまらない","eng":"boring","cn":"无聊","ne":"दिक्क लाग्छ"},
 {"kanji":"得意（な）","kana":"とくい（な）","eng":"good at (something)","cn":"拿手（的）、擅长（的）","ne":"पोख्त"},
 {"kanji":"苦手（な）","kana":"にがて（な）","eng":"bad at (something)","cn":"不擅长（的）","ne":"कमजोर"},
 {"kanji":"無理（な）","kana":"むり（な）","eng":"unable to do (something)","cn":"不可能（的）、难以做到（的）","ne":"असम्भव"},
 {"kanji":"朝早く","kana":"あさはやく","eng":"early morning","cn":"一早","ne":"बिहान सबेर"},
 {"kanji":"字幕","kana":"じまく","eng":"subtitles","cn":"字幕","ne":"अक्षरमा लेखिएको, सबटाइटल"},
 {"kanji":"大好き（な）","kana":"だいすき（な）","eng":"favorite","cn":"非常喜欢（的）","ne":"एकदम मनपर्ने"},
 {"kanji":"だいたい","kana":"だいたい","eng":"mostly, most of the time","cn":"大概、差不多","ne":"लगभग"},
 {"kanji":"まず","kana":"まず","eng":"at first (at beginning of a sentence)","cn":"首先","ne":"सबभन्दा पहिले"},
],
2: [
 {"kanji":"ファスナー","kana":"","eng":"fastener (example: zipper, velcro, etc.)","cn":"拉链","ne":"फसनर"},
 {"kanji":"うれしい","kana":"うれしい","eng":"happy, glad","cn":"高兴","ne":"खुशी लाग्छ"},
 {"kanji":"ボタン","kana":"","eng":"button","cn":"纽扣、按钮","ne":"टाँक"},
 {"kanji":"恥ずかしい","kana":"はずかしい","eng":"embarrassing","cn":"害羞、不好意思","ne":"लाज लाग्छ"},
 {"kanji":"次","kana":"つぎ","eng":"next","cn":"下一（个）","ne":"त्यसपछि/अर्को"},
 {"kanji":"違う","kana":"ちがう","eng":"differ from, be different","cn":"不一样","ne":"फरक"},
 {"kanji":"もう一度","kana":"もういちど","eng":"one more time, again","cn":"再一次","ne":"फेरि एक पटक"},
 {"kanji":"イメージ・する","kana":"","eng":"imagine, visualize","cn":"想象","ne":"कल्पना गर्नु"},
 {"kanji":"説明・する","kana":"せつめい・する","eng":"explain","cn":"说明","ne":"वर्णन गर्नु"},
 {"kanji":"腕時計","kana":"うでどけい","eng":"wristwatch","cn":"手表","ne":"हाते घडी"},
 {"kanji":"配達・する","kana":"はいたつ・する","eng":"deliver","cn":"送货","ne":"डेलिभर गर्नु"},
 {"kanji":"指輪","kana":"ゆびわ","eng":"ring","cn":"戒指","ne":"औंठी"},
 {"kanji":"コート","kana":"","eng":"coat","cn":"大衣","ne":"कोट"},
 {"kanji":"重い","kana":"おもい","eng":"heavy (weight)","cn":"重","ne":"गहुङो"},
 {"kanji":"コートを着る","kana":"コートをきる","eng":"“put on a coat”","cn":"穿大衣","ne":"कोट लगाउनु"},
 {"kanji":"軽い","kana":"かるい","eng":"light (weight)","cn":"轻","ne":"हलुका"},
 {"kanji":"ちょうどいい","kana":"ちょうどいい","eng":"perfect","cn":"正合适","ne":"एकदम ठीक्क"},
 {"kanji":"ジーンズ","kana":"","eng":"jeans","cn":"牛仔裤","ne":"जिन्स"},
 {"kanji":"セーター","kana":"","eng":"sweater","cn":"毛衣","ne":"सुइटर"},
 {"kanji":"丈夫（な）","kana":"じょうぶ（な）","eng":"sturdy","cn":"结实（的）","ne":"बलियो"},
 {"kanji":"もっと","kana":"もっと","eng":"more","cn":"更、再……一点","ne":"अझ बढी"},
 {"kanji":"画面","kana":"がめん","eng":"screen","cn":"画面","ne":"स्क्रिन"},
 {"kanji":"もっと大きいかばんがほしい","kana":"もっとおおきいかばんがほしい","eng":"“I want a larger bag”","cn":"我想要再大一点的包","ne":"अझ ठूलो झोला चाहन्छु"},
 {"kanji":"サイズ","kana":"","eng":"size","cn":"尺寸、尺码","ne":"साइज"},
 {"kanji":"数字","kana":"すうじ","eng":"number","cn":"数字","ne":"सङ्ख्या"},
 {"kanji":"ちょっと","kana":"ちょっと","eng":"a little","cn":"有点、稍微","ne":"अलिकति..."},
 {"kanji":"スーツケース","kana":"","eng":"suitcase","cn":"旅行箱","ne":"सुटकेस"},
 {"kanji":"いかがですか","kana":"いかがですか","eng":"“How is it?”","cn":"您觉得怎么样","ne":"तपाईंलाई कस्तो लाग्छ?"},
 {"kanji":"棚","kana":"たな","eng":"shelf","cn":"架子、货架","ne":"दराज"},
 {"kanji":"かしこまりました","kana":"かしこまりました","eng":"“I understand” (humble language)","cn":"明白了","ne":"हुन्छ, जो आज्ञा!"},
 {"kanji":"取っ手","kana":"とって","eng":"handle, knob","cn":"把手","ne":"ह्यान्डल"},
 {"kanji":"ヒール","kana":"","eng":"(high) heels","cn":"鞋跟","ne":"हील"},
 {"kanji":"意味","kana":"いみ","eng":"meaning","cn":"意思","ne":"अर्थ"},
 {"kanji":"ソースをかける","kana":"ソースをかける","eng":"put sauce on (something)","cn":"浇调味汁","ne":"सस हाल्नु"},
 {"kanji":"両替・する","kana":"りょうがえ・する","eng":"exchange for small money","cn":"换零钱","ne":"पैसा चेन्ज गर्नु"},
 {"kanji":"営業中","kana":"えいぎょうちゅう","eng":"open (for business)","cn":"营业中","ne":"खुला रहेको"},
 {"kanji":"定休日","kana":"ていきゅうび","eng":"regular holiday","cn":"休息日","ne":"तोकिएको बिदा"},
 {"kanji":"割引・する","kana":"わりびき・する","eng":"discount","cn":"打折、减价","ne":"डिस्काउन्ट गर्नु"},
 {"kanji":"得（な）","kana":"とく（な）","eng":"good at (something)","cn":"合算（的）","ne":"लाभदायक"},
 {"kanji":"大盛り","kana":"おおもり","eng":"extra-large helping","cn":"大份","ne":"खानाको रास"},
 {"kanji":"おかわり","kana":"おかわり","eng":"refill, second helping","cn":"再来一碗（份）","ne":"खाना थप्ने"},
 {"kanji":"どういう","kana":"どういう","eng":"what kind of","cn":"什么","ne":"कस्तो खालको"},
 {"kanji":"もう～（例：もう一杯）","kana":"もう～（れい：もういっぱい）","eng":"another ～, more ～ (example: “one more drink”)","cn":"再……（例：再来一杯）","ne":"अर्को ～ (जस्तै: अर्को एक कप)"},
 {"kanji":"親子丼","kana":"おやこどん","eng":"oyako-don (bowl of rice topped with boiled chicken and eggs)","cn":"亲子盖饭","ne":"ओयाकोदोन (अण्डा र कुखुराको मासुको परिकार)"},
 {"kanji":"牛丼","kana":"ぎゅうどん","eng":"gyu-don (bowl of rice topped with seasoned beef)","cn":"牛肉盖饭","ne":"ग्युदोन (गाईको मासुको परिकार)"},
 {"kanji":"サンドイッチ","kana":"","eng":"sandwich","cn":"三明治","ne":"स्यान्डवीच"},
 {"kanji":"ソース","kana":"","eng":"sauce","cn":"沙司、调味汁","ne":"सस"},
 {"kanji":"とんかつにソースをかける","kana":"とんかつにソースをかける","eng":"“put sauce on pork cutlet”","cn":"给猪排浇调味汁","ne":"तोनकाचुमा सस हाल्ने"},
 {"kanji":"折りたたみ傘","kana":"おりたたみがさ","eng":"folding umbrella","cn":"折叠伞","ne":"पटाउन मिल्ने छाता"},
 {"kanji":"リュックサック","kana":"","eng":"rucksack, backpack","cn":"双肩背包","ne":"ब्याकप्याक"},
 {"kanji":"デザート","kana":"","eng":"dessert","cn":"甜食","ne":"डेजर्ट"},
 {"kanji":"背負う","kana":"せおう","eng":"carry on one’s back","cn":"背","ne":"पछाडि बोक्छु"},
 {"kanji":"大変","kana":"たいへん","eng":"very","cn":"很、非常","ne":"एकदम"},
 {"kanji":"セット","kana":"","eng":"set","cn":"套餐","ne":"सेट"},
 {"kanji":"ドリンクバー","kana":"","eng":"self-service drink area in a restaurant","cn":"自助饮料区","ne":"ड्रिंक बार"},
 {"kanji":"壁","kana":"かべ","eng":"wall","cn":"墙","ne":"भित्ता"},
 {"kanji":"カレンダー","kana":"","eng":"calendar","cn":"日历","ne":"क्यालेन्डर"},
 {"kanji":"期間限定","kana":"きかんげんてい","eng":"limited period","cn":"期间限定","ne":"निश्चित अवधिसम्मको लागि"},
 {"kanji":"最新","kana":"さいしん","eng":"latest, newest","cn":"最新","ne":"नवीनतम"},
 {"kanji":"商品","kana":"しょうひん","eng":"product, goods","cn":"商品","ne":"बिक्रिको समान"},
 {"kanji":"世界地図","kana":"せかいちず","eng":"world map","cn":"世界地图","ne":"विश्वको नक्सा"},
 {"kanji":"送料","kana":"そうりょう","eng":"shipping charges","cn":"送货费","ne":"ढुवानी खर्च"},
 {"kanji":"タイムサービス","kana":"","eng":"limited time offer","cn":"时段优惠","ne":"टाइम सर्भिस"},
 {"kanji":"半額","kana":"はんがく","eng":"half-price","cn":"半价","ne":"५०% डिस्काउन्ट"},
 {"kanji":"フロアガイド","kana":"","eng":"floor guide","cn":"楼层指南","ne":"फ्लोर गाइड"},
 {"kanji":"本日","kana":"ほんじつ","eng":"today","cn":"今天","ne":"आज"},
 {"kanji":"量","kana":"りょう","eng":"amount","cn":"分量","ne":"मात्रा"},
 {"kanji":"～券（例：割引券）","kana":"～けん（れい：わりびきけん）","eng":"ticket (example: discount ticket, coupon)","cn":"…券（例：优惠券）","ne":"~टिकट (जस्तो: डिस्काउन्ट टिकट)"},
 {"kanji":"～放題（例：飲み放題）","kana":"～ほうだい（れい：のみほうだい）","eng":"all-you-can ～ (example: “all-you-can-drink”)","cn":"自由……、随意……（例：自由畅饮）","ne":"～सकाजति (जस्तै: सकाजति पिउने)"},
 {"kanji":"貼る","kana":"はる","eng":"affix","cn":"贴","ne":"टास्नु"},
 {"kanji":"かける","kana":"かける","eng":"hang, attach, put on (something)","cn":"挂、浇","ne":"झुन्ड्याउनु, हाल्नु"},
 {"kanji":"カレンダーをかける","kana":"カレンダーをかける","eng":"hang up a calendar","cn":"挂日历","ne":"क्यालेन्डर झुन्ड्याउनु"},
],
3: [
 {"kanji":"日本語能力試験","kana":"にほんごのうりょくしけん","eng":"Japanese Language Proficiency Test","cn":"日语能力测试","ne":"जापानी भाषा योग्यता परिक्षा"},
 {"kanji":"笑顔","kana":"えがお","eng":"smile","cn":"笑脸、笑容","ne":"हसमुख"},
 {"kanji":"ビジネス","kana":"","eng":"business","cn":"商务","ne":"विजिनेस/व्यावसायिक"},
 {"kanji":"悲しい","kana":"かなしい","eng":"sad","cn":"悲伤、伤心、难过","ne":"दु:ख"},
 {"kanji":"法律","kana":"ほうりつ","eng":"law","cn":"法律","ne":"कानून"},
 {"kanji":"間違い","kana":"まちがい","eng":"mistake","cn":"错误","ne":"गल्ती, गलत"},
 {"kanji":"アクセサリー","kana":"","eng":"jewelry","cn":"饰品","ne":"गरगहना"},
 {"kanji":"目標","kana":"もくひょう","eng":"goal, target","cn":"目标","ne":"लक्ष्य"},
 {"kanji":"学部","kana":"がくぶ","eng":"academic department","cn":"系、学院","ne":"संकाय, कोर्ष"},
 {"kanji":"寮","kana":"りょう","eng":"dormitory","cn":"宿舍","ne":"छात्रावास"},
 {"kanji":"カナダ","kana":"","eng":"Canada","cn":"加拿大","ne":"क्यानाडा"},
 {"kanji":"～会社（例：旅行会社）","kana":"～かいしゃ（れい：りょこうがいしゃ）","eng":"～ company (example: travel company)","cn":"……公司（例：旅游公司）","ne":"～कार्यालय (जस्तै: ट्र्राभल एजेन्सीका कार्यालय)"},
 {"kanji":"給料","kana":"きゅうりょう","eng":"salary","cn":"工资","ne":"तलब"},
 {"kanji":"～料（例：授業料）","kana":"～りょう（れい：じゅぎょうりょう）","eng":"charges, fees (example: tuition)","cn":"……费（例：学费）","ne":"～शुल्क (जस्तो: पढाइ शुल्क)"},
 {"kanji":"計画","kana":"けいかく","eng":"plan, program, project","cn":"计划","ne":"योजना"},
 {"kanji":"経済","kana":"けいざい","eng":"economics, economy","cn":"经济","ne":"अर्थशास्त्र"},
 {"kanji":"選ぶ","kana":"えらぶ","eng":"select, choose","cn":"选择","ne":"छनौट गर्नु"},
 {"kanji":"見学会","kana":"けんがくかい","eng":"observation tour","cn":"参观会","ne":"अवलोकन समारोह"},
 {"kanji":"悩む","kana":"なやむ","eng":"be troubled over, be worried about","cn":"烦恼、伤脑筋","ne":"चिन्तान्तामा हुनु"},
 {"kanji":"答え","kana":"こたえ","eng":"answer, response","cn":"答案、回答","ne":"उत्तर"},
 {"kanji":"開く","kana":"ひらく","eng":"open","cn":"开","ne":"खोल्नु"},
 {"kanji":"サークル","kana":"","eng":"club, group","cn":"社团、部","ne":"सर्कल"},
 {"kanji":"自分の店を開く","kana":"じぶんのみせをひらく","eng":"open your own store","cn":"开自己的商店","ne":"आफ्नो पसल खोल्नु"},
 {"kanji":"試験","kana":"しけん","eng":"examination","cn":"考试","ne":"परीक्षा"},
 {"kanji":"迷う","kana":"まよう","eng":"waver, hesitate","cn":"犹豫","ne":"कन्फ्युज हुनु (निर्णय गर्न नसक्नु)"},
 {"kanji":"将来","kana":"しょうらい","eng":"future","cn":"将来","ne":"भविष्यमा"},
 {"kanji":"説明会","kana":"せつめいかい","eng":"explanatory meeting","cn":"说明会","ne":"ब्रीफिङ, छलफल समारोह"},
 {"kanji":"国へ帰るかどうか迷っている","kana":"くにへかえるかどうかまよっている","eng":"“wavering whether to return to my country or not”","cn":"正犹豫着回不回国","ne":"आफ्नो देशमा जाने कि नजाने भनि निर्णय गर्न नसकेको"},
 {"kanji":"専門学校","kana":"せんもんがっこう","eng":"vocational school","cn":"专科学校","ne":"प्राविधिक विद्यालय"},
 {"kanji":"受ける","kana":"うける","eng":"receive, take","cn":"应、参加","ne":"(परीक्षा) दिनु, भाग लिनु"},
 {"kanji":"聴解","kana":"ちょうかい","eng":"listening comprehension","cn":"听力理解","ne":"सुनाइ बुझाइ जाँच"},
 {"kanji":"入学試験を受ける","kana":"にゅうがくしけんをうける","eng":"take an entrance examination","cn":"参加入学考试","ne":"प्रवेश परीक्षा दिनु"},
 {"kanji":"体験・する","kana":"たいけん・する","eng":"experience","cn":"体验、经历","ne":"अनुभव गर्नु"},
 {"kanji":"デッサン・する","kana":"","eng":"produce a drawing","cn":"素描","ne":"स्केच कोर्नु"},
 {"kanji":"考える","kana":"かんがえる","eng":"think about","cn":"考虑","ne":"सोच्छु"},
 {"kanji":"復習・する","kana":"ふくしゅう・する","eng":"review (a lesson)","cn":"复习","ne":"पुन:अध्ययन गर्नु"},
 {"kanji":"決める","kana":"きめる","eng":"decide","cn":"决定","ne":"निर्णय गर्नु"},
 {"kanji":"予習・する","kana":"よしゅう・する","eng":"prepare for (a lesson)","cn":"预习","ne":"पूर्व अध्ययन गर्नु"},
 {"kanji":"調べる","kana":"しらべる","eng":"examine","cn":"调查","ne":"खोजतलास गर्नु"},
 {"kanji":"続ける","kana":"つづける","eng":"continue","cn":"继续","ne":"निरन्तरता दिनु"},
 {"kanji":"パティシエ","kana":"","eng":"pastry baker (from the French word pâtissier)","cn":"糕点师","ne":"पेस्ट्री शेफ"},
 {"kanji":"辞める","kana":"やめる","eng":"stop, quit","cn":"辞去","ne":"गर्न छोड्नु"},
 {"kanji":"案内・する","kana":"あんない・する","eng":"guide","cn":"向导、引导","ne":"गाइड गर्नु"},
 {"kanji":"通訳・する","kana":"つうやく・する","eng":"interpret (translate orally)","cn":"翻译","ne":"उल्था/व्याख्या गर्नु"},
 {"kanji":"確認・する","kana":"かくにん・する","eng":"confirm, check","cn":"确认","ne":"सोधपुछ गरी निश्चय गर्नु"},
 {"kanji":"見学・する","kana":"けんがく・する","eng":"tour, observe","cn":"参观","ne":"अवलोकन गर्नु"},
 {"kanji":"合格・する","kana":"ごうかく・する","eng":"pass (an examination)","cn":"及格、考上","ne":"उत्तीर्ण हुनु"},
 {"kanji":"進学・する","kana":"しんがく・する","eng":"proceed to higher education","cn":"升学","ne":"उच्च शिक्षाको पढाइ गर्नु"},
 {"kanji":"就職・する","kana":"しゅうしょく・する","eng":"find a job","cn":"就业","ne":"नोकरी सुरु गर्नु"},
 {"kanji":"専攻・する","kana":"せんこう・する","eng":"specialize in, major in","cn":"专业、专修","ne":"मेजर गर्नु"},
 {"kanji":"相談・する","kana":"そうだん・する","eng":"consult with, ask someone’s advice","cn":"商量","ne":"सरसल्लाह लिनु"},
 {"kanji":"貯金・する","kana":"ちょきん・する","eng":"save up money","cn":"存钱","ne":"बचत गर्नु"},
 {"kanji":"通学・する","kana":"つうがく・する","eng":"commute to school","cn":"上学","ne":"विद्यालय आउने जाने गर्नु"},
 {"kanji":"翻訳・する","kana":"ほんやく・する","eng":"translate","cn":"翻译","ne":"अनुवाद गर्नु"},
 {"kanji":"正しい","kana":"ただしい","eng":"correct","cn":"正确","ne":"उचित"},
 {"kanji":"一生懸命","kana":"いっしょうけんめい","eng":"(do) one’s very best","cn":"拼命地、努力","ne":"मिहेनतका साथ"},
 {"kanji":"願書","kana":"がんしょ","eng":"application","cn":"申请书、报名书","ne":"आवेदन फारम"},
 {"kanji":"建築家","kana":"けんちくか","eng":"architect","cn":"建筑师","ne":"वास्तुकार"},
 {"kanji":"事務室","kana":"じむしつ","eng":"office","cn":"事务室、办公室","ne":"अफिस कोठा"},
 {"kanji":"書類","kana":"しょるい","eng":"documents","cn":"资料","ne":"कागज पत्र"},
 {"kanji":"スーツ","kana":"","eng":"business suit","cn":"西装","ne":"सुट"},
 {"kanji":"デザイナー","kana":"","eng":"designer","cn":"设计师","ne":"डिजाइनर"},
 {"kanji":"夢","kana":"ゆめ","eng":"dream (here: aspiration)","cn":"梦、梦想","ne":"सपना"},
 {"kanji":"将来の夢","kana":"しょうらいのゆめ","eng":"(one’s) future dream","cn":"未来的梦想","ne":"भविष्यको सपना"},
 {"kanji":"～中（例：今日中）","kana":"～ちゅう（れい：きょうじゅう）","eng":"during (a period) (example: during today)","cn":"……之内（例：今天之内）","ne":"～भित्र (जस्तो: आजको दिनभित्र)"},
 {"kanji":"頑張る","kana":"がんばる","eng":"do one’s best","cn":"加油、努力","ne":"मिहेनत गर्नु"},
 {"kanji":"経営・する","kana":"けいえい・する","eng":"manage (a business)","cn":"经营","ne":"सञ्चालन गर्नु"},
 {"kanji":"受験・する","kana":"じゅけん・する","eng":"take an examination","cn":"应考","ne":"परिक्षा दिनु"},
 {"kanji":"スピーチ・する","kana":"","eng":"give a speech","cn":"演讲","ne":"स्पिच (भाषण) गर्नु"},
],
4: [
 {"kanji":"茶道","kana":"さどう","eng":"sado (traditional Japanese tea ceremony)","cn":"茶道","ne":"सादो (जापानी चिया पद्दति)"},
 {"kanji":"味","kana":"あじ","eng":"taste, flavor","cn":"味道","ne":"स्वाद"},
 {"kanji":"おばさん","kana":"おばさん","eng":"ma’am (familiar term for an older woman or one’s own aunt)","cn":"姑母、伯母、姨母、舅母、阿姨","ne":"काकी"},
 {"kanji":"三味線","kana":"しゃみせん","eng":"shamisen (three-stringed Japanese musical instrument)","cn":"三味线、日本三弦琴","ne":"स्यामिसेन (एक किसिमको बाजा)"},
 {"kanji":"タコ","kana":"","eng":"octopus","cn":"章鱼","ne":"अक्टोपस"},
 {"kanji":"市民","kana":"しみん","eng":"citizen","cn":"市民","ne":"नगरवासी"},
 {"kanji":"たこ焼き","kana":"たこやき","eng":"takoyaki (fried octopus dumpling balls)","cn":"章鱼小丸子","ne":"ताकोयाकि"},
 {"kanji":"種類","kana":"しゅるい","eng":"type","cn":"种类","ne":"प्रकार"},
 {"kanji":"情報","kana":"じょうほう","eng":"information","cn":"信息","ne":"सूचना/खबर"},
 {"kanji":"水道","kana":"すいどう","eng":"waterworks, waterway","cn":"水道","ne":"पानीको धारा"},
 {"kanji":"タオル","kana":"","eng":"towel","cn":"毛巾","ne":"रुमाल"},
 {"kanji":"通る","kana":"とおる","eng":"pass through","cn":"走过、通过","ne":"यहाँ भएर जान्छ"},
 {"kanji":"似る","kana":"にる","eng":"be similar to","cn":"像","ne":"मिल्न जान्छ"},
 {"kanji":"丸い","kana":"まるい","eng":"round","cn":"圆、圆形","ne":"गोलो"},
 {"kanji":"てんぷら","kana":"","eng":"tempura (battered and deep-fried vegetables and seafood)","cn":"天妇罗","ne":"तेलमा पकाएको पकौडा जस्तो परिकार"},
 {"kanji":"小さな","kana":"ちいさな","eng":"small","cn":"小的","ne":"सानो"},
 {"kanji":"～がする","kana":"～がする","eng":"make a (noise, smell)","cn":"发出……（的气味）","ne":"～आउनु"},
 {"kanji":"方法","kana":"ほうほう","eng":"method, technique, way of doing something","cn":"方法","ne":"उपाय"},
 {"kanji":"理由","kana":"りゆう","eng":"reason","cn":"理由、原因","ne":"कारण"},
 {"kanji":"～場（例：サッカー場）","kana":"～じょう（れい：サッカーじょう）","eng":"place, location (example: soccer field)","cn":"……场（例：足球场）","ne":"～शाला (जस्तो: फुटबल रंगशाला)"},
 {"kanji":"～センター（例：市民センター）","kana":"～センター（れい：しみんセンター）","eng":"～ center (example: community center)","cn":"……中心（例：市民中心）","ne":"～केन्द्र (जस्तै: नागरिक केन्द्र)"},
 {"kanji":"～口（例：西口）","kana":"～ぐち（れい：にしぐち）","eng":"entrance, exit (example: west exit)","cn":"……口（例：西口）","ne":"～द्वार (जस्तो पश्चिमी द्वार)"},
 {"kanji":"空港","kana":"くうこう","eng":"airport","cn":"机场","ne":"एअरपोर्ट"},
 {"kanji":"歯科","kana":"しか","eng":"dentist","cn":"牙科","ne":"दन्त क्लिनिक"},
 {"kanji":"市役所","kana":"しやくしょ","eng":"city hall","cn":"市政府","ne":"नगर पालिकाको कार्यालय"},
 {"kanji":"小学校","kana":"しょうがっこう","eng":"elementary school","cn":"小学","ne":"प्राथमिक विद्यालय"},
 {"kanji":"美容院","kana":"びよういん","eng":"beauty salon","cn":"美容院","ne":"ब्युटि क्लिनिक"},
 {"kanji":"不動産","kana":"ふどうさん","eng":"real estate","cn":"房地产、不动产","ne":"रियल एस्टेट एजेन्ट, घर जग्गा बेचबिखन गर्ने कार्यालय"},
 {"kanji":"交流会","kana":"こうりゅうかい","eng":"(cultural) exchange meeting","cn":"交流会","ne":"सद्भावना समारोह"},
 {"kanji":"着く","kana":"つく","eng":"arrive","cn":"到达、抵达","ne":"पुग्छु"},
 {"kanji":"止まる","kana":"とまる","eng":"stop","cn":"停止","ne":"रोकिनु"},
 {"kanji":"水が止まる","kana":"みずがとまる","eng":"the water has stopped running","cn":"水流停止了","ne":"पानी रोकिनु"},
 {"kanji":"知らせる","kana":"しらせる","eng":"notify, inform","cn":"通知","ne":"थाहा दिनु"},
 {"kanji":"出る","kana":"でる","eng":"operate","cn":"运行","ne":"निस्कनु (आउनु)"},
 {"kanji":"バスが出る","kana":"バスがでる","eng":"(They) run a bus service","cn":"有巴士运行","ne":"बस प्रस्थान हुनु"},
 {"kanji":"カット・する","kana":"カット・する","eng":"cut","cn":"剪发","ne":"काट्नु"},
 {"kanji":"質問・する","kana":"しつもん・する","eng":"ask a question","cn":"提问","ne":"प्रश्न गर्नु"},
 {"kanji":"修理・する","kana":"しゅうり・する","eng":"repair","cn":"修理","ne":"मर्मत गर्नु"},
 {"kanji":"利用・する","kana":"りよう・する","eng":"use","cn":"利用","ne":"प्रयोग गर्नु"},
 {"kanji":"必要（な）","kana":"ひつよう（な）","eng":"needed, necessary","cn":"必要（的）","ne":"आवश्यक"},
 {"kanji":"区役所","kana":"くやくしょ","eng":"ward office","cn":"区政府","ne":"वडा प्रशासन कार्यालय"},
 {"kanji":"大使館","kana":"たいしかん","eng":"embassy","cn":"大使馆","ne":"राजदुतावास"},
 {"kanji":"坂","kana":"さか","eng":"hill, slope","cn":"斜坡","ne":"उकालो/ओरालो, भीर"},
 {"kanji":"次","kana":"つぎ","eng":"next","cn":"下一（个）","ne":"अर्को"},
 {"kanji":"～階建て","kana":"～かいだて","eng":"building with ～ floors","cn":"……层楼建筑","ne":"～तले"},
 {"kanji":"～番線","kana":"～ばんせん","eng":"number ～ train/subway line","cn":"……号线","ne":"～नम्बरको"},
 {"kanji":"～メートル","kana":"～メートル","eng":"meter (units of measurement)","cn":"……米","ne":"～मिटर"},
 {"kanji":"～行き（例：新宿行き）","kana":"～ゆき（れい：しんじゅくゆき）","eng":"destination (example: train/subway heading to Shinjuku)","cn":"……开往（例：开往新宿）","ne":"～जाने (जस्तो: सिन्जुकु जाने)"},
 {"kanji":"上る","kana":"のぼる","eng":"move upward","cn":"上","ne":"माथि जाने"},
 {"kanji":"下りる","kana":"おりる","eng":"move downward","cn":"下","ne":"तल जाने"},
 {"kanji":"駐車・する","kana":"ちゅうしゃ・する","eng":"park (a vehicle)","cn":"停车","ne":"पार्क गर्ने"},
 {"kanji":"中学校","kana":"ちゅうがっこう","eng":"middle school, junior high school","cn":"中学","ne":"जुनियर हाइस्कुल"},
 {"kanji":"方","kana":"ほう","eng":"towards, side","cn":"方向","ne":"तरिका"},
 {"kanji":"ラケット","kana":"","eng":"racket","cn":"球拍","ne":"र्‍याकेट"},
],
5: [
 {"kanji":"星","kana":"ほし","eng":"star","cn":"星星","ne":"तारा"},
 {"kanji":"失敗・する","kana":"しっぱい・する","eng":"fail, make a mistake","cn":"失败","ne":"असफल हुनु"},
 {"kanji":"革","kana":"かわ","eng":"leather","cn":"皮革","ne":"छाला"},
 {"kanji":"切符","kana":"きっぷ","eng":"ticket","cn":"车票","ne":"(ट्‍रेन) टिकट"},
 {"kanji":"池","kana":"いけ","eng":"pond","cn":"池塘","ne":"पोखरी"},
 {"kanji":"教科書","kana":"きょうかしょ","eng":"textbook","cn":"课本","ne":"पाठ्यपुस्तक"},
 {"kanji":"色","kana":"いろ","eng":"color","cn":"颜色","ne":"रङ्ग"},
 {"kanji":"ケース","kana":"","eng":"case","cn":"套子、盒子","ne":"केस"},
 {"kanji":"ピンク","kana":"","eng":"pink","cn":"粉红","ne":"गुलाबी रङ्ग"},
 {"kanji":"線路","kana":"せんろ","eng":"(train, subway) line","cn":"铁路线","ne":"रेल मार्ग"},
 {"kanji":"緑","kana":"みどり","eng":"green","cn":"绿色","ne":"हरियो"},
 {"kanji":"途中","kana":"とちゅう","eng":"in the middle of (doing something)","cn":"路上、中途","ne":"बिचमा"},
 {"kanji":"駅員","kana":"えきいん","eng":"station employee","cn":"站务员","ne":"स्टेशन कामदार"},
 {"kanji":"窓口","kana":"まどぐち","eng":"(ticket) counter","cn":"窗口","ne":"सोधपूछ गर्ने स्थान"},
 {"kanji":"警官","kana":"けいかん","eng":"policeman","cn":"警察","ne":"प्रहरी"},
 {"kanji":"横長","kana":"よこなが","eng":"long from side to side","cn":"长方形（的）","ne":"लामो चौडाइको"},
 {"kanji":"忘れ物","kana":"わすれもの","eng":"lost items, lost-and-found","cn":"遗失物品","ne":"बिर्ससिएको सामान"},
 {"kanji":"カード","kana":"","eng":"card","cn":"卡","ne":"कार्ड"},
 {"kanji":"ICカード","kana":"","eng":"IC card, smart card (plastic card with an embedded IC chip)","cn":"IC卡","ne":"IC कार्ड"},
 {"kanji":"大きさ","kana":"おおきさ","eng":"size","cn":"大小","ne":"आकार"},
 {"kanji":"財布にカードが入っている","kana":"さいふにカードがはいっている","eng":"“The card is in my wallet.”","cn":"钱包里有卡","ne":"पर्समा कार्ड हालेछु"},
 {"kanji":"階段","kana":"かいだん","eng":"stairs","cn":"台阶","ne":"भर्‍याङ"},
 {"kanji":"～辺（例：どの辺）","kana":"～へん（れい：どのへん）","eng":"somewhere around ～ (example: “Whereabouts?”, “Around where?”)","cn":"……附近（例：哪里）","ne":"～तिर (जस्तै: कतातिर)"},
 {"kanji":"鍵","kana":"かぎ","eng":"key","cn":"钥匙","ne":"साँचो"},
 {"kanji":"形","kana":"かたち","eng":"shape","cn":"形状","ne":"आकार"},
 {"kanji":"ハート","kana":"","eng":"heart","cn":"心、心形","ne":"मुटुको आकार"},
 {"kanji":"落とす","kana":"おとす","eng":"drop","cn":"掉","ne":"खसाल्नु"},
 {"kanji":"困る","kana":"こまる","eng":"be in trouble","cn":"为难","ne":"आपदमा पर्नु"},
 {"kanji":"転ぶ","kana":"ころぶ","eng":"fall down","cn":"摔倒、跌落","ne":"लड्नु"},
 {"kanji":"壊す","kana":"こわす","eng":"break, destroy","cn":"弄坏、破坏","ne":"बिगार्नु"},
 {"kanji":"付く","kana":"つく","eng":"attach","cn":"带有","ne":"लाग्छु"},
 {"kanji":"ポケットが付いている","kana":"ポケットがついている","eng":"“A pocket is attached.”","cn":"带有口袋","ne":"खल्ती छ।"},
 {"kanji":"なくなる","kana":"なくなる","eng":"lose (something)","cn":"丢失","ne":"हराउनु"},
 {"kanji":"自転車がなくなった","kana":"じてんしゃがなくなった","eng":"“I lost my bicycle.”","cn":"自行车丢了","ne":"साइकल हरायो"},
 {"kanji":"乗り過ごす","kana":"のりすごす","eng":"miss one’s stop","cn":"坐过站","ne":"निदाएर ओर्लन बिर्सनु"},
 {"kanji":"迷う","kana":"まよう","eng":"lose (one’s way)","cn":"迷失","ne":"कन्फ्युज हुनु"},
 {"kanji":"道に迷う","kana":"みちにまよう","eng":"get lost","cn":"迷路","ne":"बाटो कन्फ्युज हुनु"},
 {"kanji":"見つかる","kana":"みつかる","eng":"find","cn":"找到","ne":"पत्ता लाग्छु"},
 {"kanji":"出る","kana":"でる","eng":"go out, leave","cn":"出来","ne":"निस्कनु"},
 {"kanji":"駅を出る","kana":"えきをでる","eng":"leave a station","cn":"出车站","ne":"स्टेशनबाट निस्कन्छु"},
 {"kanji":"乗り換える","kana":"のりかえる","eng":"change (trains, planes)","cn":"换乘","ne":"ट्‍रान्सफर गर्नु"},
 {"kanji":"間違える","kana":"まちがえる","eng":"make a mistake","cn":"弄错、搞错","ne":"भूल गर्नु"},
 {"kanji":"心配・する","kana":"しんぱい・する","eng":"worry","cn":"担心","ne":"चिन्तान्ता गर्नु"},
 {"kanji":"連絡・する","kana":"れんらく・する","eng":"contact","cn":"联系","ne":"खबर गर्नु"},
 {"kanji":"気がつく","kana":"きがつく","eng":"notice, realize","cn":"意识到、注意到","ne":"थाहा लाग्छु"},
 {"kanji":"急に","kana":"きゅうに","eng":"suddenly","cn":"突然","ne":"अचानक"},
 {"kanji":"さっき","kana":"さっき","eng":"a moment ago","cn":"刚才","ne":"अघि"},
 {"kanji":"しばらく","kana":"しばらく","eng":"in a little while","cn":"暂时","ne":"केही छिन"},
 {"kanji":"預かる","kana":"あずかる","eng":"leave (something, someone) in someone’s care, check in (baggage)","cn":"保管","ne":"जिम्मामा लिनु"},
 {"kanji":"取る","kana":"とる","eng":"take, get","cn":"取得","ne":"लिनु"},
 {"kanji":"100点を取る","kana":"ひゃくてんをとる","eng":"get 100 points","cn":"得100分","ne":"१०० अङ्क, नम्बर ल्याउनु"},
 {"kanji":"戻る","kana":"もどる","eng":"return","cn":"返回","ne":"फर्कनु"},
 {"kanji":"変える","kana":"かえる","eng":"change","cn":"变更","ne":"बदल्नु"},
 {"kanji":"アナウンス・する","kana":"","eng":"announce","cn":"广播通知","ne":"एनाउन्स गर्नु"},
 {"kanji":"安心・する","kana":"あんしん・する","eng":"relieve (someone’s fears), give peace of mind","cn":"放心","ne":"ढुक्क हुनु"},
 {"kanji":"遅刻・する","kana":"ちこく・する","eng":"be late","cn":"迟到","ne":"अबेर हुनु"},
 {"kanji":"寝坊・する","kana":"ねぼう・する","eng":"sleep late","cn":"睡懒觉","ne":"बिहान अबेरसम्म सुत्नु"},
 {"kanji":"びっくり・する","kana":"","eng":"be surprised","cn":"吃惊","ne":"चकित हुनु"},
 {"kanji":"薄い","kana":"うすい","eng":"thin, weak, faint","cn":"薄、淡","ne":"खल्‍ो"},
 {"kanji":"この料理は味が薄い","kana":"このりょうりはあじがうすい","eng":"“This cooking has a weak flavor.”","cn":"这道菜的味道淡","ne":"यो परिकारमा स्वाद खल्‍ो छ"},
 {"kanji":"すぐ","kana":"すぐ","eng":"immediately","cn":"马上、立即","ne":"तुरुन्त"},
 {"kanji":"本当に","kana":"ほんとうに","eng":"really, truly","cn":"真的、真是","ne":"साच्चिकै"},
 {"kanji":"もう少し","kana":"もうすこし","eng":"a little more","cn":"再稍微","ne":"अझ अलिकति"},
 {"kanji":"ゆっくり","kana":"ゆっくり","eng":"slowly","cn":"慢慢地","ne":"बिस्तार"},
 {"kanji":"ゆっくり話してください","kana":"ゆっくりはなしてください","eng":"“Please speak slowly.”","cn":"请慢慢说","ne":"बिस्तार भन्नुहोला"},
 {"kanji":"全部で","kana":"ぜんぶで","eng":"altogether","cn":"总共、全部","ne":"सबै मिलाएर"},
 {"kanji":"白","kana":"しろ","eng":"white","cn":"白色（的）","ne":"सेतो"},
 {"kanji":"確かに","kana":"たしかに","eng":"I am certain that","cn":"的确是、确实是","ne":"अवश्य नै"},
 {"kanji":"～号車","kana":"～ごうしゃ","eng":"number ～ train","cn":"……号车厢","ne":"～नम्बरको ट्‍रेन"},
 {"kanji":"それが……","kana":"それが……","eng":"That is ....","cn":"那个……","ne":"हुन त हो तर…"},
 {"kanji":"～ずつ","kana":"～ずつ","eng":"every ～","cn":"每……、各……","ne":"～वटा गरी"},
 {"kanji":"どうしよう","kana":"どうしよう","eng":"What should I do?","cn":"这可怎么办","ne":"के गर्ने होला"},
 {"kanji":"急行","kana":"きゅうこう","eng":"express (train)","cn":"快车","ne":"एक्‍सप्रेस"},
 {"kanji":"特急","kana":"とっきゅう","eng":"limited express (train)","cn":"特快","ne":"लिमिटेड एक्‍सप्रेस"},
 {"kanji":"コインロッカー","kana":"","eng":"coin locker","cn":"投币式存放柜","ne":"कोइन लकर"},
 {"kanji":"終点","kana":"しゅうてん","eng":"final stop","cn":"终点站","ne":"गन्तब्य"},
 {"kanji":"終電","kana":"しゅうでん","eng":"final train","cn":"末班车","ne":"आखिरी ट्‍रेन"},
 {"kanji":"タクシー","kana":"","eng":"taxi","cn":"出租车","ne":"ट्‍याक्‍सी"},
 {"kanji":"定期券","kana":"ていきけん","eng":"commuter pass","cn":"定期车票","ne":"ट्‍रेन पास"},
 {"kanji":"箱","kana":"はこ","eng":"box","cn":"箱子、盒子","ne":"बाकस/डिब्बा"},
 {"kanji":"文字","kana":"もじ","eng":"character","cn":"文字","ne":"अक्षर"},
 {"kanji":"～点（例：100点）","kana":"～てん（れい：ひゃくてん）","eng":"point(s) (e.g., 100 points)","cn":"分（例如：100分）","ne":"～नम्बर, अङ्क (जस्तो: १०० नम्बर, अङ्क)"},
],
6: [
 {"kanji":"宿泊","kana":"しゅくはく","eng":"lodging","cn":"住宿","ne":"वास बसाइ"},
 {"kanji":"ウニ","kana":"","eng":"sea urchin","cn":"海胆","ne":"उनी (समुन्द्रि जीव)"},
 {"kanji":"水族館","kana":"すいぞくかん","eng":"aquarium","cn":"水族馆","ne":"एक्‍वुरियम"},
 {"kanji":"カヌー","kana":"","eng":"canoe","cn":"独木舟","ne":"कानु"},
 {"kanji":"スノーボード","kana":"","eng":"snowboard","cn":"滑板滑雪","ne":"स्नोबोर्ड"},
 {"kanji":"自然","kana":"しぜん","eng":"nature","cn":"自然","ne":"प्रकृति"},
 {"kanji":"代金","kana":"だいきん","eng":"charges, fees","cn":"费用","ne":"लागे खर्च"},
 {"kanji":"湿原","kana":"しつげん","eng":"marsh","cn":"湿地","ne":"ओशिलो मैदान"},
 {"kanji":"朝食","kana":"ちょうしょく","eng":"breakfast","cn":"早餐","ne":"बिहानको खाना"},
 {"kanji":"ジャガイモ","kana":"","eng":"potato","cn":"土豆","ne":"आलु"},
 {"kanji":"夕食","kana":"ゆうしょく","eng":"dinner","cn":"晚餐","ne":"बेलुकाको खाना"},
 {"kanji":"乗馬","kana":"じょうば","eng":"horseback riding","cn":"骑马","ne":"घोडचडी"},
 {"kanji":"登山","kana":"とざん","eng":"mountain climbing","cn":"爬山、登山","ne":"पर्वतारोहण"},
 {"kanji":"トウモロコシ","kana":"","eng":"corn","cn":"玉米","ne":"मकै"},
 {"kanji":"内容","kana":"ないよう","eng":"details","cn":"内容","ne":"विषय"},
 {"kanji":"牧場","kana":"ぼくじょう","eng":"ranch","cn":"牧场","ne":"गौचर"},
 {"kanji":"なし","kana":"なし","eng":"none","cn":"没有、无","ne":"नहुनु"},
 {"kanji":"ラベンダー畑","kana":"ラベンダーばたけ","eng":"Lavender Farm","cn":"薰衣草花田","ne":"लाबेन्डर फूलको बगैँचा"},
 {"kanji":"値段","kana":"ねだん","eng":"price","cn":"价格","ne":"मूल्य"},
 {"kanji":"楽しむ","kana":"たのしむ","eng":"enjoy","cn":"享受","ne":"रमाइलो गर्नु"},
 {"kanji":"船","kana":"ふね","eng":"ship, boat","cn":"船","ne":"पानी जहाज"},
 {"kanji":"プラン","kana":"","eng":"plan","cn":"计划、方案","ne":"योजना"},
 {"kanji":"大人","kana":"おとな","eng":"adult","cn":"成人","ne":"वयस्क"},
 {"kanji":"雰囲気","kana":"ふんいき","eng":"atmosphere, mood","cn":"气氛","ne":"वातावरण"},
 {"kanji":"カニ","kana":"","eng":"crab","cn":"蟹","ne":"गंगटो"},
 {"kanji":"街","kana":"まち","eng":"town","cn":"街道、市街","ne":"ठूलो शहर"},
 {"kanji":"着物","kana":"きもの","eng":"clothing","cn":"和服","ne":"किमोनो"},
 {"kanji":"虫","kana":"むし","eng":"bugs, insects","cn":"虫子","ne":"किरा फट्यांग्‍रा"},
 {"kanji":"旅館","kana":"りょかん","eng":"Japanese-style inn","cn":"旅馆","ne":"परम्परागत जापानी होटल/लज"},
 {"kanji":"こっち","kana":"こっち","eng":"this way (informal)","cn":"这边","ne":"यता"},
 {"kanji":"そっち","kana":"そっち","eng":"that way (informal)","cn":"那边","ne":"त्यता"},
 {"kanji":"～付き（例：朝食付き）","kana":"～つき（れい：ちょうしょくつき）","eng":"～ included (example: breakfast included)","cn":"带……（例：带早餐）","ne":"～सहितको (जस्तो: बिहानको खाना सहितको)"},
 {"kanji":"最後","kana":"さいご","eng":"last","cn":"最后","ne":"अन्तिम"},
 {"kanji":"～泊～日（例：2泊3日）","kana":"～はく～か（れい：にはくみっか）","eng":"～ nights ～ days (example: 2 nights 3 days)","cn":"……天……夜（例：3天2夜）","ne":"～रात ～दिन (जस्तो: २ रात ३ दिन)"},
 {"kanji":"市内","kana":"しない","eng":"within the city","cn":"市内","ne":"नगरभित्र"},
 {"kanji":"ショッピングセンター","kana":"","eng":"shopping center, mall","cn":"购物中心","ne":"शपिङ सेन्टर"},
 {"kanji":"～費（例：交通費）","kana":"～ひ（れい：こうつうひ）","eng":"～ fee (example: transportation fee)","cn":"……费（例：交通费）","ne":"～खर्‍च (जस्तो: सवारी खर्‍च)"},
 {"kanji":"どっち","kana":"どっち","eng":"which","cn":"哪一个","ne":"कुन"},
 {"kanji":"待ち合わせる","kana":"まちあわせる","eng":"meet with","cn":"碰头、集合","ne":"भेला हुनु"},
 {"kanji":"ガイド・する","kana":"","eng":"guide","cn":"向导、引导","ne":"गाइड गर्नु"},
 {"kanji":"観光・する","kana":"かんこう・する","eng":"go sightseeing, tour","cn":"观光、游览","ne":"घुमफिर गर्ने"},
 {"kanji":"キャンプ・する","kana":"","eng":"camp","cn":"野营","ne":"क्‍याम्प गर्ने"},
 {"kanji":"出発・する","kana":"しゅっぱつ・する","eng":"leave, depart","cn":"出发","ne":"प्रस्थान गर्ने"},
 {"kanji":"チェックイン・する","kana":"","eng":"check in (at a hotel)","cn":"入住、登机","ne":"भित्र पस्छु"},
 {"kanji":"レンタル・する","kana":"","eng":"rent (a car, office, etc.)","cn":"租赁","ne":"भाडामा लिनु"},
 {"kanji":"珍しい","kana":"めずらしい","eng":"unusual","cn":"少见、稀有","ne":"दुर्लभ"},
 {"kanji":"伝統的（な）","kana":"でんとうてき（な）","eng":"traditional","cn":"传统（的）","ne":"परम्परागत"},
 {"kanji":"それに","kana":"それに","eng":"also, in addition","cn":"而且","ne":"अनि त्यसका साथै"},
 {"kanji":"イルカ","kana":"","eng":"dolphin","cn":"海豚","ne":"डल्‍फिन"},
 {"kanji":"ガイドブック","kana":"","eng":"guidebook","cn":"旅游指南","ne":"गाइड बुक"},
 {"kanji":"ショー","kana":"","eng":"show","cn":"表演","ne":"प्रदर्शन"},
 {"kanji":"手袋","kana":"てぶくろ","eng":"gloves","cn":"手套","ne":"पन्जा"},
 {"kanji":"年末","kana":"ねんまつ","eng":"end of year","cn":"年底","ne":"बर्षान्त"},
 {"kanji":"マフラー","kana":"","eng":"scarf","cn":"围巾","ne":"गलबन्दी"},
 {"kanji":"～中（例：旅行中）","kana":"～ちゅう（れい：りょこうちゅう）","eng":"during ～ (example: during travel)","cn":"在……中（例：在旅行中）","ne":"～अवधिभित्र (जस्तो: यात्रा अवधिभित्र)"},
 {"kanji":"取る","kana":"とる","eng":"take","cn":"取得","ne":"लिनु"},
 {"kanji":"休みを取る","kana":"やすみをとる","eng":"take a vacation","cn":"请假","ne":"बिदा लिनु"},
 {"kanji":"なくなる","kana":"なくなる","eng":"run out, disappear, be missing","cn":"没有了","ne":"हराउनु/बित्‍नु"},
 {"kanji":"席がなくなる","kana":"せきがなくなる","eng":"“There are no more seats left.”","cn":"座位没有了","ne":"सिट हराउनु"},
 {"kanji":"伝える","kana":"つたえる","eng":"tell (someone something)","cn":"转告、传达","ne":"बताउनु, भन्नु"},
 {"kanji":"ぬれる","kana":"ぬれる","eng":"get wet","cn":"淋湿、弄湿","ne":"भिज्‍छु"},
 {"kanji":"コピー・する","kana":"","eng":"make a photocopy","cn":"复印","ne":"फोटो कपी गर्नु"},
 {"kanji":"到着・する","kana":"とうちゃく・する","eng":"to arrive","cn":"到达","ne":"(कुनै स्‍थानमा) पुग्‍छु"},
 {"kanji":"用意・する","kana":"ようい・する","eng":"prepare","cn":"准备、预备","ne":"तयारी गर्नु"},
 {"kanji":"お願いします","kana":"おねがいします","eng":"“Please (do it).”","cn":"拜托了、劳驾了","ne":"अनुरोध गर्नु"},
 {"kanji":"あとで","kana":"あとで","eng":"later","cn":"过会儿、稍后","ne":"पछि"},
],
7: [
 {"kanji":"召し上がる","kana":"めしあがる","eng":"eat, drink (respectful language)","cn":"吃、喝","ne":"खानु (आदरभाव)"},
 {"kanji":"相手","kana":"あいて","eng":"the other person","cn":"对方","ne":"कुरा गरिने व्यक्ति"},
 {"kanji":"出席・する","kana":"しゅっせき・する","eng":"attend","cn":"出席","ne":"उपस्थित हुने"},
 {"kanji":"習慣","kana":"しゅうかん","eng":"custom, tradition, habit","cn":"习惯、习俗","ne":"चाल चलन"},
 {"kanji":"退院・する","kana":"たいいん・する","eng":"leave the hospital, be discharged","cn":"出院","ne":"अस्पतालबाट डिस्चार्ज हुनु"},
 {"kanji":"違い","kana":"ちがい","eng":"difference","cn":"不同","ne":"फरक"},
 {"kanji":"驚く","kana":"おどろく","eng":"surprise","cn":"吃惊","ne":"अचम्म हुनु"},
 {"kanji":"失礼（な）","kana":"しつれい（な）","eng":"rude, impolite","cn":"失礼（的）、不礼貌（的）","ne":"अशिष्ट"},
 {"kanji":"もう一度","kana":"もういちど","eng":"one more time, again","cn":"再一次","ne":"फेरि एक पटक"},
 {"kanji":"皮","kana":"かわ","eng":"skin, peel","cn":"皮","ne":"छाला"},
 {"kanji":"カップ","kana":"","eng":"cup","cn":"杯子","ne":"कप"},
 {"kanji":"味","kana":"あじ","eng":"taste, flavor","cn":"味道","ne":"स्वाद"},
 {"kanji":"会議","kana":"かいぎ","eng":"conference, meeting","cn":"会议","ne":"सभा"},
 {"kanji":"課長","kana":"かちょう","eng":"section chief","cn":"课长","ne":"शाखाप्रमुख"},
 {"kanji":"社長","kana":"しゃちょう","eng":"company president","cn":"社长","ne":"कम्पनि प्रमुख"},
 {"kanji":"ご存じ","kana":"ごぞんじ","eng":"know (respectful language)","cn":"您知道","ne":"अवगत हुनु"},
 {"kanji":"ミステリー","kana":"","eng":"Mystery","cn":"推理小说、侦探小说","ne":"रहस्य / मिस्ट्री"},
 {"kanji":"～頃（例：9時頃）","kana":"～ごろ（れい：くじごろ）","eng":"around ～ (example: around 9:00)","cn":"……左右（例：9点左右）","ne":"～तिर (जस्तै: ९ बजेतिर)"},
 {"kanji":"どなた","kana":"どなた","eng":"who (polite)","cn":"哪位","ne":"को"},
 {"kanji":"いらっしゃる","kana":"いらっしゃる","eng":"come, go, be (respectful language)","cn":"去、来、在","ne":"आउनु (आदरभाव)"},
 {"kanji":"おっしゃる","kana":"おっしゃる","eng":"say (respectful language)","cn":"说","ne":"भन्नु (आदरभाव)"},
 {"kanji":"ご覧になる","kana":"ごらんになる","eng":"look at, see (respectful language)","cn":"看","ne":"हेर्नु (आदरभाव)"},
 {"kanji":"なさる","kana":"なさる","eng":"do (respectful language)","cn":"做","ne":"गर्नु (आदरभाव)"},
 {"kanji":"キャベツ","kana":"","eng":"cabbage","cn":"卷心菜","ne":"बन्दागोबी"},
 {"kanji":"ジャガイモ","kana":"","eng":"potato","cn":"土豆","ne":"आलु"},
 {"kanji":"大根","kana":"だいこん","eng":"Japanese radish","cn":"萝卜","ne":"मुला"},
 {"kanji":"タマネギ","kana":"","eng":"onion","cn":"洋葱","ne":"प्‍याज"},
 {"kanji":"ニンジン","kana":"","eng":"carrot","cn":"胡萝卜","ne":"गाजर मुला"},
 {"kanji":"ネギ","kana":"","eng":"green onion","cn":"葱","ne":"प्‍याजको पात"},
 {"kanji":"クリーム","kana":"","eng":"cream","cn":"奶油","ne":"क्रिम"},
 {"kanji":"コショウ","kana":"","eng":"black pepper","cn":"胡椒","ne":"धुलो मरिच"},
 {"kanji":"酢","kana":"す","eng":"vinegar","cn":"醋","ne":"भिनेगर"},
 {"kanji":"調味料","kana":"ちょうみりょう","eng":"seasonings","cn":"调味品","ne":"मरमसला"},
 {"kanji":"このくらい","kana":"このくらい","eng":"this much","cn":"差不多这么大","ne":"यति"},
 {"kanji":"ゼリー","kana":"","eng":"jello, gelatin","cn":"果冻","ne":"जेली"},
 {"kanji":"ソース","kana":"","eng":"sauce","cn":"调味汁、沙司","ne":"सस"},
 {"kanji":"パスタのソースを作る","kana":"パスタのソースをつくる","eng":"make pasta sauce","cn":"做意面的调味汁","ne":"पास्ताको सस बनाउनु"},
 {"kanji":"漬物","kana":"つけもの","eng":"pickled vegetables","cn":"腌菜","ne":"अचार"},
 {"kanji":"できあがり","kana":"できあがり","eng":"finished","cn":"做好了","ne":"तयार भएको"},
 {"kanji":"鍋","kana":"なべ","eng":"pan","cn":"锅","ne":"नाबे (कराइ)"},
 {"kanji":"パスタ","kana":"","eng":"pasta","cn":"意面","ne":"पास्ता"},
 {"kanji":"ハチミツ","kana":"","eng":"honey","cn":"蜂蜜","ne":"मह"},
 {"kanji":"火","kana":"ひ","eng":"heat","cn":"火","ne":"आगो"},
 {"kanji":"強火","kana":"つよび","eng":"strong heat","cn":"大火","ne":"ठूलो आगो"},
 {"kanji":"弱火","kana":"よわび","eng":"low heat","cn":"小火","ne":"सानो आगो"},
 {"kanji":"半分","kana":"はんぶん","eng":"half","cn":"一半","ne":"आधि"},
 {"kanji":"みそ汁","kana":"みそしる","eng":"miso soup (traditional Japanese bean paste soup)","cn":"酱汤","ne":"मिसो सुप"},
 {"kanji":"ルー","kana":"","eng":"roux, thickening agent for soup or sauce","cn":"黄油面酱","ne":"रेडिमेड मसाला"},
 {"kanji":"ローリエ","kana":"","eng":"bay leaf (from the French word laurier)","cn":"月桂叶","ne":"लौरियल"},
 {"kanji":"～グラム","kana":"～グラム","eng":"～gram","cn":"……克","ne":"～ग्‍राम"},
 {"kanji":"変わる","kana":"かわる","eng":"change","cn":"变化","ne":"बदल्नु"},
 {"kanji":"冷やす","kana":"ひやす","eng":"cool","cn":"冰镇、冷却","ne":"चिस्‍याउनु"},
 {"kanji":"むく","kana":"むく","eng":"peel","cn":"削、剥","ne":"बोक्‍रा छोडाउनु"},
 {"kanji":"焼く","kana":"やく","eng":"fry, grill, toast, bake, roast","cn":"烧、烤","ne":"पोल्नु"},
 {"kanji":"沸かす","kana":"わかす","eng":"boil (water)","cn":"烧开、煮沸","ne":"(पानी) उमाल्नु"},
 {"kanji":"炒める","kana":"いためる","eng":"fry","cn":"炒","ne":"भुट्नु"},
 {"kanji":"煮る","kana":"にる","eng":"boil (food in water)","cn":"煮","ne":"झोल हालि पकाउनु"},
 {"kanji":"ゆでる","kana":"ゆでる","eng":"boil (food, mostly vegetables or eggs, in water)","cn":"焯、烫","ne":"उमाल्नु"},
 {"kanji":"沸騰・する","kana":"ふっとう・する","eng":"bring to a boil","cn":"沸腾","ne":"उम्‍लिनु"},
 {"kanji":"厚い","kana":"あつい","eng":"thick, having wide thickness","cn":"厚","ne":"बाक्‍लो"},
 {"kanji":"薄い","kana":"うすい","eng":"thin, weak","cn":"薄、淡","ne":"पातलो"},
 {"kanji":"薄く切る","kana":"うすくきる","eng":"“Cut thinly.”","cn":"切薄片","ne":"पातलोसँग काट्नु"},
 {"kanji":"濃い","kana":"こい","eng":"dense, rich, thick","cn":"浓","ne":"कडा स्वाद"},
 {"kanji":"細かい","kana":"こまかい","eng":"fine, small","cn":"细碎","ne":"मसिनो"},
 {"kanji":"細い","kana":"ほそい","eng":"narrow","cn":"细","ne":"पातलो"},
 {"kanji":"弱い","kana":"よわい","eng":"weak","cn":"弱、小","ne":"कमजोर"},
 {"kanji":"まず","kana":"まず","eng":"at first (at beginning of a sentence)","cn":"首先","ne":"सबभन्दा पहिले"},
 {"kanji":"次に","kana":"つぎに","eng":"next","cn":"接着","ne":"त्यसपछि"},
 {"kanji":"最後に","kana":"さいごに","eng":"finally, lastly","cn":"最后","ne":"अन्तिममा"},
 {"kanji":"肉じゃが","kana":"にくじゃが","eng":"(simmered) meat and potatoes","cn":"日式土豆炖肉","ne":"निकुजागा"},
 {"kanji":"ラケット","kana":"","eng":"racket","cn":"球拍","ne":"र्‍याकेट"},
 {"kanji":"遠慮・する","kana":"えんりょ・する","eng":"refrain from, hesitate","cn":"客气","ne":"नम्रतापूर्वक अस्वीकार गर्नु"},
 {"kanji":"だいたい","kana":"だいたい","eng":"mostly, most of the time","cn":"大概、差不多","ne":"लगभग"},
 {"kanji":"もちろん","kana":"もちろん","eng":"of course","cn":"当然、不用说","ne":"अवश्य"},
 {"kanji":"お邪魔します","kana":"おじゃまします","eng":"excuse me for interrupting, excuse me for intruding","cn":"打扰了","ne":"केही बेर दु:ख दिन्छु (कसैको घरमा जाँदा भनिने)"},
 {"kanji":"よくいらっしゃいました","kana":"よくいらっしゃいました","eng":"thank you for coming","cn":"欢迎","ne":"स्वागत छ"},
],
8: [
 {"kanji":"拾う","kana":"ひろう","eng":"pick up","cn":"拾、捡","ne":"भुइँबाट उठाउनु"},
 {"kanji":"明るい","kana":"あかるい","eng":"bright","cn":"明亮","ne":"उज्‍यालो"},
 {"kanji":"譲る","kana":"ゆずる","eng":"pass on, transfer to","cn":"让给、转让","ne":"कसैका लागि छोडिदिनु"},
 {"kanji":"やっと","kana":"やっと","eng":"finally","cn":"终于","ne":"बल्ल"},
 {"kanji":"助ける","kana":"たすける","eng":"help, save","cn":"帮助","ne":"मदत गर्नु"},
 {"kanji":"届ける","kana":"とどける","eng":"send, deliver","cn":"送到","ne":"पुर्‍याउनु"},
 {"kanji":"お巡りさん","kana":"おまわりさん","eng":"policeman","cn":"巡警","ne":"प्रहरी"},
 {"kanji":"迎えに来る","kana":"むかえにくる","eng":"come get (someone)","cn":"来接","ne":"लिन आउनु"},
 {"kanji":"クッキー","kana":"","eng":"cookie","cn":"曲奇","ne":"कुक्की/बिस्कुट"},
 {"kanji":"（お）団子","kana":"（お）だんご","eng":"rice dumpling","cn":"丸子串","ne":"लड्डु"},
 {"kanji":"肉じゃが","kana":"にくじゃが","eng":"(simmered) meat and potatoes","cn":"日式土豆炖肉","ne":"निकुजागा"},
 {"kanji":"そんなに","kana":"そんなに","eng":"like that, so much","cn":"（不）那么","ne":"त्यति धेरै त"},
 {"kanji":"ふーん","kana":"ふーん","eng":"well ...","cn":"嗯……","ne":"ए हो र?"},
 {"kanji":"鏡","kana":"かがみ","eng":"mirror","cn":"镜子","ne":"ऐना"},
 {"kanji":"湖","kana":"みずうみ","eng":"lake","cn":"湖","ne":"ताल"},
 {"kanji":"花瓶","kana":"かびん","eng":"flower vase","cn":"花瓶","ne":"फुलदानी"},
 {"kanji":"教授","kana":"きょうじゅ","eng":"professor","cn":"教授","ne":"प्रोफेसर"},
 {"kanji":"～さん（例：駅員さん）","kana":"～さん（れい：えきいんさん）","eng":"Mr./Mrs./Miss/Ms., added to certain professions as a term of respect (example: station employee)","cn":"……师傅（例：站务员师傅）","ne":"～ज्‍यु (जस्तो: स्टेशन कर्‍्मचारीज्‍यु)"},
 {"kanji":"近所","kana":"きんじょ","eng":"neighborhood","cn":"附近、近处","ne":"छिमेक"},
 {"kanji":"この間","kana":"このあいだ","eng":"the other day, during this time","cn":"前几天","ne":"केही समय अगाडि"},
 {"kanji":"送る","kana":"おくる","eng":"send off, take (someone somewhere)","cn":"送","ne":"पठाउनु/पुर्‍याउनु"},
 {"kanji":"資料","kana":"しりょう","eng":"documents, information materials","cn":"资料","ne":"कागज पत्र"},
 {"kanji":"車でうちまで送る","kana":"くるまでうちまでおくる","eng":"take someone home by car","cn":"用车送（你）到家","ne":"गाडीद्वारा घरसम्म पुर्‍याउनु"},
 {"kanji":"（お）茶碗","kana":"（お）ちゃわん","eng":"china cup, china bowl","cn":"碗","ne":"कचौरा"},
 {"kanji":"連れて行く","kana":"つれていく","eng":"take someone along","cn":"带去","ne":"लिएर जानु"},
 {"kanji":"机","kana":"つくえ","eng":"desk","cn":"桌子","ne":"टेबुल"},
 {"kanji":"捕る","kana":"とる","eng":"catch","cn":"抓、捉","ne":"पक्रनु"},
 {"kanji":"人形","kana":"にんぎょう","eng":"doll, figure","cn":"玩偶","ne":"पुतली"},
 {"kanji":"直す","kana":"なおす","eng":"fix, correct, repair","cn":"修理、修改","ne":"मर्मत गर्नु"},
 {"kanji":"部長","kana":"ぶちょう","eng":"department manager","cn":"部长","ne":"विभाग प्रमुख"},
 {"kanji":"本棚","kana":"ほんだな","eng":"bookshelf","cn":"书架","ne":"पुस्तकको दराज"},
 {"kanji":"（お）礼","kana":"（お）れい","eng":"thanks, appreciation","cn":"感谢、谢意","ne":"आभार"},
 {"kanji":"～先（例：アルバイト先）","kana":"～さき（れい：アルバイトさき）","eng":"place where ～ (example: place where you work part-time)","cn":"……地方（例如：打工的地方）","ne":"～मा (पार्‍टटाइम काममा)"},
 {"kanji":"いただく","kana":"いただく","eng":"(gratefully) receive (humble language referring to oneself)","cn":"领受","ne":"प्राप्त गर्नु"},
 {"kanji":"くださる","kana":"くださる","eng":"(gratefully) receive from someone (respectful language referring to someone else)","cn":"给（我）","ne":"दिनु"},
 {"kanji":"うれしい","kana":"うれしい","eng":"happy","cn":"高兴","ne":"खुशी"},
 {"kanji":"気持ちいい","kana":"きもちいい","eng":"comfortable, pleasant","cn":"舒服、舒畅","ne":"आनन्द/मन राम्रो"},
 {"kanji":"素敵（な）","kana":"すてき（な）","eng":"splendid/ wonderful","cn":"漂亮（的）","ne":"अति सुन्दर/आकर्षक"},
 {"kanji":"どういたしまして","kana":"どういたしまして","eng":"You’re welcome","cn":"不客气","ne":"केही छैन"},
 {"kanji":"チヂミ","kana":"","eng":"chijimi (Korean-style pancake)","cn":"韩式煎饼","ne":"चिजिमी (कोरियन खाना)"},
 {"kanji":"におい","kana":"におい","eng":"smell","cn":"气味","ne":"वास्ना, गन्ध"},
 {"kanji":"飾る","kana":"かざる","eng":"decorate","cn":"装饰、装点","ne":"सजाउनु"},
 {"kanji":"いろんな","kana":"いろんな","eng":"various","cn":"各种各样的","ne":"अनेक थरिका/विभिन्न"},
 {"kanji":"乾杯","kana":"かんぱい","eng":"“Bottoms up!”, “Cheers”","cn":"干杯","ne":"चियर्स गर्नु"},
],
9: [
 {"kanji":"月","kana":"つき","eng":"month","cn":"月","ne":"महिना, चन्द्रमा, सोम (बार)"},
 {"kanji":"大切さ","kana":"たいせつさ","eng":"importance","cn":"重要性","ne":"महत्व"},
 {"kanji":"前の月","kana":"まえのつき","eng":"the previous month","cn":"上个月","ne":"अघिल्‍लो महिना"},
 {"kanji":"恥ずかしい","kana":"はずかしい","eng":"embarrassing","cn":"害羞、不好意思","ne":"लाजलाग्छो"},
 {"kanji":"都合","kana":"つごう","eng":"schedule","cn":"方便","ne":"अनुकुल अवस्था"},
 {"kanji":"伝票","kana":"でんぴょう","eng":"order slip","cn":"小票","ne":"विल"},
 {"kanji":"ですから","kana":"ですから","eng":"therefore","cn":"因此","ne":"त्यसकारणले"},
 {"kanji":"道具","kana":"どうぐ","eng":"tool","cn":"工具","ne":"समान"},
 {"kanji":"一度","kana":"いちど","eng":"once, one time","cn":"一次","ne":"एक पटक"},
 {"kanji":"表","kana":"ひょう","eng":"table, chart","cn":"表格","ne":"तालिका"},
 {"kanji":"裏","kana":"うら","eng":"rear","cn":"后面、背面","ne":"पछाडि, भित्र पट्टि"},
 {"kanji":"ホール","kana":"","eng":"hall","cn":"大厅","ne":"हल"},
 {"kanji":"毎月","kana":"まいつき","eng":"every month","cn":"每月","ne":"प्रत्येक महिना"},
 {"kanji":"オーブン","kana":"","eng":"oven","cn":"烤箱","ne":"ओभन"},
 {"kanji":"温度","kana":"おんど","eng":"temperature","cn":"温度","ne":"तापक्रम"},
 {"kanji":"マニュアル","kana":"","eng":"manual","cn":"操作手册","ne":"म्‍यानुअल"},
 {"kanji":"紙","kana":"かみ","eng":"paper","cn":"纸","ne":"कागज"},
 {"kanji":"床","kana":"ゆか","eng":"floor","cn":"地面","ne":"भुइँ"},
 {"kanji":"髪の毛","kana":"かみのけ","eng":"hair","cn":"头发","ne":"कपाल"},
 {"kanji":"汚れ","kana":"よごれ","eng":"dirtiness","cn":"污垢","ne":"फोहोर"},
 {"kanji":"代わり","kana":"かわり","eng":"in place of","cn":"代替","ne":"बदलामा"},
 {"kanji":"予定","kana":"よてい","eng":"schedule, plan","cn":"预定","ne":"योजना"},
 {"kanji":"シフト","kana":"","eng":"shift","cn":"轮班时间","ne":"सिफ्ट"},
 {"kanji":"ルール","kana":"","eng":"rule","cn":"规则","ne":"नियम"},
 {"kanji":"シール","kana":"","eng":"sticker, seal","cn":"封条","ne":"स्टिकर"},
 {"kanji":"スタッフ","kana":"","eng":"staff","cn":"员工","ne":"स्‍टाफ"},
 {"kanji":"スニーカー","kana":"","eng":"sneakers","cn":"运动鞋","ne":"स्निकर जुत्ता"},
 {"kanji":"～様（例：お客様）","kana":"～さま（れい：おきゃくさま）","eng":"sir, madam (more respectful than san; used with customers, etc.)","cn":"……先生、……女士（例：称呼客人时）","ne":"～ज्‍यु (जस्तो: अतिथिज्‍यु)"},
 {"kanji":"上がる","kana":"あがる","eng":"rise","cn":"上升、涨","ne":"वृद्धि हुनु"},
 {"kanji":"隅","kana":"すみ","eng":"corner","cn":"角落","ne":"कुना"},
 {"kanji":"空く","kana":"あく","eng":"become empty, vacant","cn":"空、空出","ne":"खाली हुनु"},
 {"kanji":"洗剤","kana":"せんざい","eng":"detergent, cleanser","cn":"洗涤剂","ne":"डिटर्जेेन्ट, वासिङ पाउडर"},
 {"kanji":"押す","kana":"おす","eng":"punch","cn":"打","ne":"दबाउनु/हाल्नु"},
 {"kanji":"タイムカード","kana":"","eng":"time card","cn":"考勤卡","ne":"टाइम कार्ड"},
 {"kanji":"タイムカードを押す","kana":"タイムカードをおす","eng":"punch a time card","cn":"打考勤卡","ne":"टाइम कार्ड हाल्नु"},
 {"kanji":"誰か","kana":"だれか","eng":"someone","cn":"谁","ne":"कोही"},
 {"kanji":"乾く","kana":"かわく","eng":"dry","cn":"干","ne":"सुक्‍छु"},
 {"kanji":"調理場","kana":"ちょうりば","eng":"cooking place, kitchen (of a restaurant)","cn":"厨房","ne":"किचन, भान्‍छाघर"},
 {"kanji":"代わる","kana":"かわる","eng":"replace","cn":"代替","ne":"बदली हुनु"},
 {"kanji":"アルバイトを代わる","kana":"アルバイトをかわる","eng":"replace someone’s shift","cn":"代替别人打工","ne":"पार्‍ट टाइम काम बदल्नु"},
 {"kanji":"断る","kana":"ことわる","eng":"turn down, deny","cn":"拒绝","ne":"अस्वीकार गर्नु"},
 {"kanji":"しまう","kana":"しまう","eng":"put away","cn":"收起、收纳","ne":"थन्क्‍याउनु"},
 {"kanji":"滑る","kana":"すべる","eng":"slide","cn":"滑","ne":"चिप्लनु"},
 {"kanji":"モップ","kana":"","eng":"mop","cn":"拖把","ne":"भुइँ पुछ्ने मप"},
 {"kanji":"出す","kana":"だす","eng":"take out, come out","cn":"拿出去、倒出去","ne":"निकाल्नु"},
 {"kanji":"～袋（例：ごみ袋）","kana":"～ぶくろ（れい：ごみぶくろ）","eng":"～ bag (example: garbage bag)","cn":"……袋（例：垃圾袋）","ne":"～झोला (जस्तो: फोहोरको झोला)"},
 {"kanji":"ごみを出す","kana":"ごみをだす","eng":"take out the garbage","cn":"把垃圾倒掉","ne":"फोहोर निकाल्नु"},
 {"kanji":"決まる","kana":"きまる","eng":"decide","cn":"决定","ne":"निश्चित हुनु"},
 {"kanji":"運ぶ","kana":"はこぶ","eng":"carry","cn":"搬运","ne":"ओसार्नु"},
 {"kanji":"届く","kana":"とどく","eng":"reach","cn":"到达","ne":"पुग्‍छु"},
 {"kanji":"拭く","kana":"ふく","eng":"wipe","cn":"擦、抹","ne":"पुछ्नु"},
 {"kanji":"かける","kana":"かける","eng":"rest on, sit","cn":"坐","ne":"लगाउनु/बस्‍छु"},
 {"kanji":"こちらのいすにおかけください","kana":"こちらのいすにおかけください","eng":"“Please have a seat here.”","cn":"请坐在这边的椅子上","ne":"कृपया यहाँको मेचमा बस्नुहोस्"},
 {"kanji":"干す","kana":"ほす","eng":"hang out to dry","cn":"晾、晒","ne":"सुकाउनु"},
 {"kanji":"呼ぶ","kana":"よぶ","eng":"call","cn":"呼叫","ne":"बोलाउनु"},
 {"kanji":"渡す","kana":"わたす","eng":"hand over","cn":"交给","ne":"दिनु"},
 {"kanji":"切れる","kana":"きれる","eng":"run out of","cn":"断开","ne":"काटिनु/सिद्धिनु"},
 {"kanji":"焦げる","kana":"こげる","eng":"get burned","cn":"焦、糊","ne":"डढ्नु"},
 {"kanji":"上げる","kana":"あげる","eng":"raise","cn":"升高","ne":"उचाल्नु"},
 {"kanji":"確かめる","kana":"たしかめる","eng":"make sure, confirm","cn":"确认","ne":"निश्चित गर्नु"},
 {"kanji":"下げる","kana":"さげる","eng":"lower","cn":"降低","ne":"ओराल्नु"},
 {"kanji":"破れる","kana":"やぶれる","eng":"break","cn":"破裂","ne":"च्यातिनु"},
 {"kanji":"片付ける","kana":"かたづける","eng":"clean up","cn":"收拾、整理","ne":"सामान ठीकठाउँमा राख्‍छु"},
 {"kanji":"着替える","kana":"きがえる","eng":"change clothes","cn":"换衣服","ne":"लुगा बदल्नु"},
 {"kanji":"休憩・する","kana":"きゅうけい・する","eng":"take a break","cn":"休息","ne":"विश्‍राम गर्नु"},
 {"kanji":"注意・する","kana":"ちゅうい・する","eng":"pay attention","cn":"注意","ne":"सचेत गर्नु"},
 {"kanji":"足りる","kana":"たりる","eng":"be enough","cn":"足够","ne":"पुग्‍छु"},
 {"kanji":"ご注意ください","kana":"ごちゅういください","eng":"“Pay attention.”","cn":"请注意","ne":"ध्यान दिनुहोला"},
 {"kanji":"つける","kana":"つける","eng":"attach, put on","cn":"佩带","ne":"लगाउनु"},
 {"kanji":"アクセサリーをつける","kana":"アクセサリーをつける","eng":"put on jewelry","cn":"佩带首饰","ne":"गरगहना लगाउनु"},
 {"kanji":"少々","kana":"しょうしょう","eng":"a little bit","cn":"一些、稍微","ne":"अलिकति"},
 {"kanji":"並べる","kana":"ならべる","eng":"line up","cn":"摆放、排列","ne":"लाइनमा राख्‍छु"},
 {"kanji":"お先にどうぞ","kana":"おさきにどうぞ","eng":"Please go ahead","cn":"您先请","ne":"अगाडि जानोस्"},
 {"kanji":"燃える","kana":"もえる","eng":"burn","cn":"燃烧","ne":"जल्नु"},
 {"kanji":"ご自由に","kana":"ごじゆうに","eng":"Please feel free","cn":"请随意","ne":"खुला मनले"},
 {"kanji":"挨拶・する","kana":"あいさつ・する","eng":"greet","cn":"问候、寒暄","ne":"अभिवादन गर्नु"},
 {"kanji":"申し訳ないんですが","kana":"もうしわけないんですが","eng":"I am sorry, but ...","cn":"非常抱歉","ne":"कृपया माफ गर्नुहोला कि"},
 {"kanji":"おしゃべり・する","kana":"おしゃべり・する","eng":"talk, chat","cn":"闲谈","ne":"कुराकानी गर्नु"},
 {"kanji":"チェック・する","kana":"","eng":"check","cn":"打记号","ne":"चेक गर्नु"},
 {"kanji":"気をつける","kana":"きをつける","eng":"be careful","cn":"当心、留神","ne":"ध्यान राख्नु"},
 {"kanji":"邪魔（な）","kana":"じゃま（な）","eng":"distraction, hindrance","cn":"妨碍、碍事","ne":"बाधा"},
 {"kanji":"最初に","kana":"さいしょに","eng":"first of all","cn":"首先","ne":"सुरुमा"},
 {"kanji":"丁寧（な）","kana":"ていねい（な）","eng":"polite","cn":"很有礼貌","ne":"बुझ्ने गरी"},
 {"kanji":"先に","kana":"さきに","eng":"before, in front, in first","cn":"先","ne":"पहिले"},
 {"kanji":"しっかり","kana":"しっかり","eng":"properly, adequately","cn":"用力地、好好地","ne":"राम्रोसँग"},
 {"kanji":"絶対に","kana":"ぜったいに","eng":"absolutely","cn":"绝对","ne":"अवश्य पनि"},
 {"kanji":"はっきり","kana":"はっきり","eng":"clearly","cn":"清楚、鲜明","ne":"स्पस्‍ट"},
 {"kanji":"大きな","kana":"おおきな","eng":"large","cn":"大、大的","ne":"ठूलो"},
 {"kanji":"お手洗い","kana":"おてあらい","eng":"washroom, toilet","cn":"卫生间","ne":"टोइलेट"},
 {"kanji":"ガス","kana":"","eng":"gas","cn":"煤气","ne":"ग्‍यास"},
 {"kanji":"ガソリン","kana":"","eng":"gasoline","cn":"汽油","ne":"पेट्‍रोल"},
 {"kanji":"そのまま","kana":"そのまま","eng":"as is, without change","cn":"原封不动、照旧","ne":"जस्तो छ त्यस्तै"},
 {"kanji":"バター","kana":"","eng":"butter","cn":"黄油","ne":"बटर"},
 {"kanji":"引き出し","kana":"ひきだし","eng":"drawer","cn":"抽屉","ne":"ड्‍रयर"},
 {"kanji":"ひも","kana":"ひも","eng":"string","cn":"线、绳","ne":"डोरी"},
 {"kanji":"袋","kana":"ふくろ","eng":"bag, pouch","cn":"袋子","ne":"झोला"},
 {"kanji":"瓶","kana":"びん","eng":"bottle, jar","cn":"瓶","ne":"बोटल"},
],
10: [
 {"kanji":"係","kana":"かかり","eng":"person in charge","cn":"负责人","ne":"इन्चार्‍ज"},
 {"kanji":"あめ","kana":"あめ","eng":"candy, sweets","cn":"饴糖","ne":"क्‍यान्डी"},
 {"kanji":"シカ","kana":"","eng":"deer","cn":"鹿","ne":"जरायो"},
 {"kanji":"王様","kana":"おうさま","eng":"king","cn":"国王","ne":"महाराज"},
 {"kanji":"シングル","kana":"","eng":"single","cn":"单人间","ne":"सिङ्गल"},
 {"kanji":"クルミ","kana":"","eng":"walnut","cn":"核桃","ne":"ओखर"},
 {"kanji":"ツイン","kana":"","eng":"twin","cn":"双人间","ne":"ट्विन"},
 {"kanji":"ゴマ","kana":"","eng":"sesame","cn":"芝麻","ne":"तील"},
 {"kanji":"展望台","kana":"てんぼうだい","eng":"viewing platform","cn":"眺望台、观景台","ne":"अवलोकन बाल्कुनी"},
 {"kanji":"泥棒","kana":"どろぼう","eng":"thief, burglar","cn":"小偷","ne":"चोर"},
 {"kanji":"誰でも","kana":"だれでも","eng":"anyone","cn":"不论是谁都","ne":"जो कोही पनि"},
 {"kanji":"バッテリー","kana":"","eng":"battery (esp. rechargeable battery)","cn":"充电电池、蓄电池","ne":"ब्याट्‍्री"},
 {"kanji":"フロント","kana":"","eng":"front desk","cn":"前台","ne":"फ्रन्ट"},
 {"kanji":"ポーチ","kana":"","eng":"pouch","cn":"小手袋","ne":"पाउच / थैली"},
 {"kanji":"ライブ","kana":"","eng":"live (concert, broadcast)","cn":"演唱会","ne":"लाइभ"},
 {"kanji":"伸ばす","kana":"のばす","eng":"stretch, extend","cn":"伸开、拉长","ne":"लम्काउनु"},
 {"kanji":"ロック","kana":"","eng":"rock","cn":"摇滚","ne":"रक म्युजिक"},
 {"kanji":"巻く","kana":"まく","eng":"wind up, wrap around","cn":"卷、缠","ne":"बाँध्नु"},
 {"kanji":"かむ","kana":"かむ","eng":"chew","cn":"咬","ne":"टोक्‍छु"},
 {"kanji":"丸い","kana":"まるい","eng":"round","cn":"圆、圆形","ne":"गोलो"},
 {"kanji":"配る","kana":"くばる","eng":"distribute","cn":"分发","ne":"बाँड्नु"},
 {"kanji":"刺す","kana":"さす","eng":"bite, sting, stick with","cn":"咬、叮、蜇","ne":"घोच्‍छु"},
 {"kanji":"誘う","kana":"さそう","eng":"invite, take out","cn":"邀请、约","ne":"निम्त्याउनु"},
 {"kanji":"頼む","kana":"たのむ","eng":"ask, request","cn":"托付、委托","ne":"अनुरोध गर्नु"},
 {"kanji":"踏む","kana":"ふむ","eng":"step on","cn":"踩","ne":"कुल्चनु"},
 {"kanji":"ぶつかる","kana":"ぶつかる","eng":"hit, run against","cn":"碰、撞","ne":"ठोक्किनु"},
 {"kanji":"蚊","kana":"か","eng":"mosquito","cn":"蚊子","ne":"लामखुट्‍टे"},
 {"kanji":"けんか・する","kana":"けんか・する","eng":"argue","cn":"吵架、打架","ne":"झगडा गर्नु"},
 {"kanji":"おじいさん","kana":"おじいさん","eng":"an old man","cn":"爷爷","ne":"हजुरबुबा"},
 {"kanji":"近所のおじいさん","kana":"きんじょのおじいさん","eng":"an old man in the neighbourhood","cn":"近邻的爷爷","ne":"छिमेकको हजुरबुबा"},
 {"kanji":"おばあさん","kana":"おばあさん","eng":"an old woman","cn":"婆婆","ne":"हजुरआमा"},
 {"kanji":"近所のおばあさん","kana":"きんじょのおばあさん","eng":"an old woman in the neighbourhood","cn":"附近的婆婆","ne":"छिमेककी हजुरआमा"},
 {"kanji":"おにぎり","kana":"おにぎり","eng":"rice ball","cn":"饭团","ne":"ओनिगिरी"},
 {"kanji":"撮影・する","kana":"さつえい・する","eng":"take a picture, record video","cn":"摄影、拍摄","ne":"छायांकन गर्नु"},
 {"kanji":"充電・する","kana":"じゅうでん・する","eng":"charge (a battery)","cn":"充电","ne":"चार्‍ज गर्नु"},
 {"kanji":"招待・する","kana":"しょうたい・する","eng":"invite, ask","cn":"招待","ne":"निमन्त्रणा गर्नु"},
 {"kanji":"タッチ・する","kana":"","eng":"touch, tap (a screen)","cn":"触碰","ne":"छुनु"},
 {"kanji":"注意・する","kana":"ちゅうい・する","eng":"advise, admonish","cn":"提醒","ne":"सचेत गराउनु"},
 {"kanji":"係の人に注意される","kana":"かかりのひとにちゅういされる","eng":"be given notice by the staff","cn":"被工作人员提醒","ne":"सम्बन्धित कर्‍्मचारीद्वारा सचेत गराइनु"},
 {"kanji":"通訳・する","kana":"つうやく・する","eng":"interpret (translate orally)","cn":"翻译","ne":"उल्‍था / व्याख्या गर्नु"},
 {"kanji":"発売・する","kana":"はつばい・する","eng":"sell","cn":"出售","ne":"बिक्री गर्नु"},
 {"kanji":"うまい","kana":"うまい","eng":"taste good, delicious","cn":"好","ne":"मीठो"},
 {"kanji":"いっぱい","kana":"いっぱい","eng":"full","cn":"很多","ne":"थुप्रै"},
 {"kanji":"あれ？","kana":"あれ？","eng":"What?","cn":"啊？","ne":"ओ हो, के हो?(आश्चर्‍य मान्दा प्रयोग हुने)"},
 {"kanji":"アイスクリーム","kana":"","eng":"ice cream","cn":"冰淇淋","ne":"आइसक्रिम"},
 {"kanji":"博物館","kana":"はくぶつかん","eng":"museum","cn":"博物馆","ne":"संग्रहालय"},
 {"kanji":"プロ","kana":"","eng":"pro, professional","cn":"职业","ne":"पेशेवर"},
 {"kanji":"ミルク","kana":"","eng":"milk","cn":"奶","ne":"दुध"},
 {"kanji":"麦","kana":"むぎ","eng":"wheat, barley, flour","cn":"麦子","ne":"गहुँ/जौ"},
 {"kanji":"向こう","kana":"むこう","eng":"over there, the opposite (other) side","cn":"对面、那边","ne":"उतापट्टि"},
 {"kanji":"屋根","kana":"やね","eng":"roof","cn":"屋顶","ne":"छाना"},
 {"kanji":"ヨーロッパ","kana":"","eng":"Europe","cn":"欧洲","ne":"युरोप"},
 {"kanji":"～時代（例：江戸時代）","kana":"～じだい（れい：えどじだい）","eng":"～ period (example: Edo period)","cn":"……时代（例：江户时代）","ne":"～युग/काल (जस्तो: एदो काल)"},
 {"kanji":"～中（例：世界中）","kana":"～じゅう（れい：せかいじゅう）","eng":"all over ～, throughout ～ (example: all over the world)","cn":"全……（例：全世界）","ne":"～भरि (जस्तो: विश्व भरि)"},
 {"kanji":"～箱（例：弁当箱）","kana":"～ばこ（れい：べんとうばこ）","eng":"～ box (example: bento box)","cn":"……盒（例：便当盒）","ne":"～बाकस (जस्तै: खाजाबाकस)"},
 {"kanji":"行う","kana":"おこなう","eng":"perform","cn":"做、干、进行","ne":"गर्नु"},
 {"kanji":"造る","kana":"つくる","eng":"create, build","cn":"制造","ne":"बनाउनु"},
 {"kanji":"開く","kana":"ひらく","eng":"open, hold","cn":"举行","ne":"खोल्नु/आयोजना गर्नु"},
 {"kanji":"コンサートが開かれる","kana":"コンサートがひらかれる","eng":"hold a concert","cn":"举行音乐会","ne":"कन्सर्‍टको आयोजना हुनु"},
 {"kanji":"向かう","kana":"むかう","eng":"leave for, face (a certain direction)","cn":"朝着、前往","ne":"तिर लाग्‍छु"},
 {"kanji":"生きる","kana":"いきる","eng":"live, to be alive","cn":"活着","ne":"जिउनु"},
 {"kanji":"生まれる","kana":"うまれる","eng":"be born","cn":"诞生、出生","ne":"जन्मनु"},
 {"kanji":"建てる","kana":"たてる","eng":"build","cn":"建造","ne":"निर्माण गर्नु"},
 {"kanji":"逃げる","kana":"にげる","eng":"run away, escape","cn":"逃","ne":"भाग्‍छु"},
 {"kanji":"設計・する","kana":"せっけい・する","eng":"design, plan","cn":"设计","ne":"योजना बनाउनु"},
 {"kanji":"発見・する","kana":"はっけん・する","eng":"find, discover","cn":"发现","ne":"पत्ता लगाउनु"},
 {"kanji":"発明・する","kana":"はつめい・する","eng":"invent","cn":"发明","ne":"आविश्कार गर्नु"},
 {"kanji":"～によって","kana":"～によって","eng":"due to ～","cn":"根据……","ne":"～द्वारा"},
 {"kanji":"赤ちゃん","kana":"あかちゃん","eng":"baby","cn":"婴儿","ne":"शिशु, बच्चा"},
 {"kanji":"あっち","kana":"あっち","eng":"(over) there (informal)","cn":"那边、那里","ne":"त्यतातिर"},
 {"kanji":"鉛筆","kana":"えんぴつ","eng":"pencil","cn":"铅笔","ne":"पेन्सिल"},
 {"kanji":"多く","kana":"おおく","eng":"many","cn":"许多、多数","ne":"धेरैजसो"},
 {"kanji":"お化け屋敷","kana":"おばけやしき","eng":"haunted house","cn":"鬼屋","ne":"भूतको घर"},
 {"kanji":"おやき","kana":"おやき","eng":"oyaki (Japanese dumpling popular in Nagano prefecture)","cn":"御烧、烤菜包（日式烤菜包，长野县的乡土食品）","ne":"ओयाकि मिठाइ"},
 {"kanji":"会場","kana":"かいじょう","eng":"meeting place, conference hall","cn":"会场","ne":"समारोह स्थल"},
 {"kanji":"カタカナ","kana":"","eng":"Japanese katakana script","cn":"片假名","ne":"काताकाना अक्षर"},
 {"kanji":"工場","kana":"こうじょう","eng":"factory","cn":"工厂","ne":"कारखाना"},
 {"kanji":"国際","kana":"こくさい","eng":"international","cn":"国际","ne":"अन्तर्राष्ट्रिय"},
 {"kanji":"子ども","kana":"こども","eng":"child, kid","cn":"孩子","ne":"बच्चा"},
 {"kanji":"近所の子ども","kana":"きんじょのこども","eng":"neighborhood child","cn":"近邻的孩子","ne":"छिमेकका बच्चा"},
 {"kanji":"柔道","kana":"じゅうどう","eng":"judo","cn":"柔道","ne":"जुडो"},
 {"kanji":"世界","kana":"せかい","eng":"world","cn":"世界","ne":"विश्व"},
 {"kanji":"月","kana":"つき","eng":"moon","cn":"月亮、月","ne":"चन्द्रमा"},
 {"kanji":"月を見る","kana":"つきをみる","eng":"see the moon","cn":"赏月","ne":"चन्द्रमा हेर्नु"},
 {"kanji":"電池","kana":"でんち","eng":"battery (esp. dry cell battery)","cn":"电池","ne":"ब्याट्‍्री"},
 {"kanji":"トラ","kana":"","eng":"tiger","cn":"老虎","ne":"बाघ"},
 {"kanji":"遠く","kana":"とおく","eng":"far away","cn":"远、远处","ne":"टाढा"},
 {"kanji":"乗り場","kana":"のりば","eng":"platform, gate, loading zone","cn":"乘车站","ne":"चढ्ने ठाउँ"},
 {"kanji":"ロープウエー","kana":"","eng":"ropeway","cn":"缆车","ne":"केबुलकार"},
 {"kanji":"ちょうど","kana":"ちょうど","eng":"exactly, precisely","cn":"正好","ne":"ठिक्क"},
 {"kanji":"お待たせ","kana":"おまたせ","eng":"“Sorry to keep you waiting”","cn":"让你久等了","ne":"पर्खनु परेकोमा माफ दिनोस्"},
],
11: [
 {"kanji":"違い","kana":"ちがい","eng":"difference","cn":"不同、差异","ne":"फरक"},
 {"kanji":"おじさん","kana":"おじさん","eng":"uncle, mister (polite term used to refer to middle-aged men)","cn":"大叔、大伯","ne":"काका/मामा"},
 {"kanji":"物価","kana":"ぶっか","eng":"prices of commodities","cn":"物价","ne":"सामानको मूल्य"},
 {"kanji":"苦労","kana":"くろう","eng":"trouble, burden","cn":"辛苦","ne":"दु:ख"},
 {"kanji":"文化","kana":"ぶんか","eng":"culture","cn":"文化","ne":"संस्कृति"},
 {"kanji":"八百屋","kana":"やおや","eng":"vegetable vendor, green grocery","cn":"蔬菜水果店","ne":"तरकारी पसल, सब्जिदार"},
 {"kanji":"ボランティア","kana":"","eng":"volunteer","cn":"志愿者","ne":"भोलन्टियर"},
 {"kanji":"無理","kana":"むり","eng":"overdo, take something too far","cn":"过度","ne":"जबरजस्ति/असम्भव"},
 {"kanji":"話しかける","kana":"はなしかける","eng":"talk to, speak to","cn":"搭话、攀谈","ne":"कुरा गर्न लाग्‍छु"},
 {"kanji":"親しい","kana":"したしい","eng":"familiar, intimate","cn":"亲切、亲密","ne":"निकट सम्बन्धको"},
 {"kanji":"何度も","kana":"なんども","eng":"over and over again, many times","cn":"好几次","ne":"धेरै पटक"},
 {"kanji":"～代（例：食事代）","kana":"～だい（れい：しょくじだい）","eng":"～ charges, ～ fees (example: dining charges)","cn":"……费（例：餐费）","ne":"～खर्‍च (जस्तो: खाना खर्‍च)"},
 {"kanji":"持つ","kana":"もつ","eng":"have, hold","cn":"有、感","ne":"साथमा राख्‍छु/लिनु"},
 {"kanji":"興味を持つ","kana":"きょうみをもつ","eng":"have an interest","cn":"有兴趣","ne":"चाख राख्‍छु"},
 {"kanji":"学ぶ","kana":"まなぶ","eng":"learn, study","cn":"学习","ne":"सिक्‍छु"},
 {"kanji":"彼女","kana":"かのじょ","eng":"girlfriend","cn":"女友","ne":"त्यो आइमाइ /गर्‍लफ्रेण्ड"},
 {"kanji":"彼","kana":"かれ","eng":"boyfriend","cn":"男友","ne":"त्यो मान्‍छे /बोइफ्रेण्ड"},
 {"kanji":"折れる","kana":"おれる","eng":"break","cn":"折断","ne":"भाँचिनु"},
 {"kanji":"答える","kana":"こたえる","eng":"answer, respond","cn":"回答","ne":"उत्तर दिनु"},
 {"kanji":"育てる","kana":"そだてる","eng":"raise (a child), bring up","cn":"培育","ne":"हुर्काउनु"},
 {"kanji":"国の彼女／彼に会いたい","kana":"くにのかのじょかれにあいたい","eng":"“I miss my girlfriend/boyfriend back home.”","cn":"想见祖国的女朋友（男朋友）","ne":"देशको गर्‍लफ्रेण्ड /बोइफ्रेण्डलाई भेट्न चाहन्‍छु"},
 {"kanji":"記者","kana":"きしゃ","eng":"journalist, reporter","cn":"记者","ne":"रिपोर्‍टर"},
 {"kanji":"興味","kana":"きょうみ","eng":"interest","cn":"爱好","ne":"चाख/चासो"},
 {"kanji":"インタビュー・する","kana":"","eng":"interview","cn":"进行采访","ne":"अन्तरवार्ता गर्नु"},
 {"kanji":"外食・する","kana":"がいしょく・する","eng":"dine out, eat out","cn":"在外就餐","ne":"बाहिर खाना खानु"},
 {"kanji":"敬語","kana":"けいご","eng":"respectful language","cn":"敬语","ne":"आदरका कुराहरू/आदरार्थी शब्द"},
 {"kanji":"研究・する","kana":"けんきゅう・する","eng":"research","cn":"研究","ne":"अनुसन्‍धान गर्नु"},
 {"kanji":"故障・する","kana":"こしょう・する","eng":"get out of order, break down","cn":"出故障","ne":"बिग्रनु"},
 {"kanji":"将来のこと","kana":"しょうらいのこと","eng":"things about the future","cn":"将来的事","ne":"भविष्यको कुरा"},
 {"kanji":"節約・する","kana":"せつやく・する","eng":"economize, be thrifty","cn":"节约","ne":"बचत गर्नु"},
 {"kanji":"地域","kana":"ちいき","eng":"region, area, zone, locality","cn":"地区、区域","ne":"क्षेत्र"},
 {"kanji":"あんまり","kana":"あんまり","eng":"not much, not very","cn":"太、过于","ne":"त्यति धेरै त...."},
 {"kanji":"だいたい","kana":"だいたい","eng":"mostly, most of the time","cn":"大概","ne":"लगभग"},
 {"kanji":"運転手","kana":"うんてんしゅ","eng":"driver","cn":"司机","ne":"ड्‍राइभर"},
 {"kanji":"駅前","kana":"えきまえ","eng":"in front of the train station","cn":"车站前","ne":"स्‍टेशन अगाडि"},
 {"kanji":"具合","kana":"ぐあい","eng":"condition, health","cn":"身体状况","ne":"अवस्था(शारीरिक)"},
 {"kanji":"今夜","kana":"こんや","eng":"tonight","cn":"今晚","ne":"आज राती"},
 {"kanji":"打つ","kana":"うつ","eng":"hit","cn":"击、打","ne":"हान्नु"},
 {"kanji":"回る","kana":"まわる","eng":"go around","cn":"绕、转","ne":"घुम्‍छु"},
 {"kanji":"諦める","kana":"あきらめる","eng":"give up","cn":"断念、放弃","ne":"मन मार्‍नु"},
 {"kanji":"投げる","kana":"なげる","eng":"throw","cn":"投、扔","ne":"हुत्याउनु"},
 {"kanji":"出張・する","kana":"しゅっちょう・する","eng":"go on a business trip","cn":"出差","ne":"काजमा जानु"},
 {"kanji":"機会","kana":"きかい","eng":"chance, opportunity","cn":"机会","ne":"अवसर"},
 {"kanji":"～君","kana":"～くん","eng":"(suffix for boy’s names that indicates respect and familiarity)","cn":"小……、老……","ne":"…ज्‍यु"},
 {"kanji":"シュート・する","kana":"","eng":"shoot","cn":"射（球）","ne":"सुट हान्नु"},
 {"kanji":"お帰りなさい","kana":"おかえりなさい","eng":"“Welcome home.”","cn":"你回来了、欢迎回家","ne":"फर्केर आएकोमा स्वागत"},
 {"kanji":"よし","kana":"よし","eng":"good, come on","cn":"好","ne":"ल त"},
],
12: [
 {"kanji":"傘をさす","kana":"かさをさす","eng":"open an umbrella","cn":"撑伞","ne":"छाता ओढ्नु"},
 {"kanji":"インスタント","kana":"","eng":"instant","cn":"方便、速食","ne":"पूर्‍व तयारिको(रेडिमेड)"},
 {"kanji":"酔う","kana":"よう","eng":"get drunk, feel sick (at the stomach)","cn":"醉","ne":"रक्‍सी लाग्‍छु"},
 {"kanji":"食品","kana":"しょくひん","eng":"food","cn":"食品","ne":"खाद्य पदार्‍थ"},
 {"kanji":"取れる","kana":"とれる","eng":"relieve, break free from","cn":"消除、去除","ne":"लिन/निकाल्न सकिनु"},
 {"kanji":"残す","kana":"のこす","eng":"leave, save","cn":"剩下","ne":"बाँकी राख्‍छु"},
 {"kanji":"アドバイス・する","kana":"","eng":"give advice, advise","cn":"建议","ne":"सल्लाह दिनु"},
 {"kanji":"残る","kana":"のこる","eng":"be left remaining","cn":"余下","ne":"बाँकी हुनु"},
 {"kanji":"入会・する","kana":"にゅうかい・する","eng":"join, become a member of a group","cn":"入会","ne":"सदस्य हुनु"},
 {"kanji":"冷凍・する","kana":"れいとう・する","eng":"freeze","cn":"冷冻","ne":"फ्रिज गराउनु"},
 {"kanji":"ガンガン","kana":"","eng":"pounding, throbbing (state where it feels as if the pain in your head is making a loud sound)","cn":"疼得厉害（就像脑中发出很大的声响，形容头疼剧烈的样子）","ne":"झम झम(टाउको दुख्‍दा अनुभव हुने एक किसिमको दुखाइ)"},
 {"kanji":"胃","kana":"い","eng":"stomach","cn":"胃","ne":"पेट"},
 {"kanji":"痛み","kana":"いたみ","eng":"pain","cn":"疼、痛","ne":"दुख्‍छु"},
 {"kanji":"うがい","kana":"うがい","eng":"gargling","cn":"漱口","ne":"घाँटी कुला गर्ने"},
 {"kanji":"元気","kana":"げんき","eng":"healthy, lively, spirited","cn":"精神、健康","ne":"सञ्चो"},
 {"kanji":"氷","kana":"こおり","eng":"ice","cn":"冰","ne":"आइस/बरफ"},
 {"kanji":"湿布","kana":"しっぷ","eng":"cold (hot) compress","cn":"膏药","ne":"पानीपट्‍टी, कम्पेस"},
 {"kanji":"ジム","kana":"","eng":"gym, gymnasium","cn":"健身房","ne":"जिम"},
 {"kanji":"疲れ","kana":"つかれ","eng":"fatigue, tiredness","cn":"疲倦","ne":"थकाइ"},
 {"kanji":"ドレッシング","kana":"","eng":"dressing","cn":"调味汁","ne":"ड्‍्रेसिङ"},
 {"kanji":"様子","kana":"ようす","eng":"appearance","cn":"情况","ne":"अवस्‍था"},
 {"kanji":"～金（例：入会金）","kana":"～きん（れい：にゅうかいきん）","eng":"～ fee, ～ charge (example: admission fee)","cn":"……费（例：入会费）","ne":"～रकम (जस्तो: सदस्य हुनमा लाग्‍ने रकम)"},
 {"kanji":"さす","kana":"さす","eng":"hold over one’s head","cn":"撑","ne":"छाता लगाउनु / उघार्नु"},
 {"kanji":"パンパン","kana":"","eng":"tense, full (state where it feels as if your muscles are being stretched tightly)","cn":"涨涨的（肌肉等僵硬肿胀的样子）","ne":"टनक्क (सुन्निनु)"},
 {"kanji":"フラフラ","kana":"","eng":"groggy, dizzy, woozy (state where you cannot gather any energy, are weary, or your body is unsteady)","cn":"摇摇晃晃、晕晕乎乎（因使不上劲、疲倦等原因，感觉身体好像在摇晃的样子）","ne":"लरखर"},
 {"kanji":"ムカムカ","kana":"","eng":"nauseous, queasy (state where you feel like you are going to vomit due to overeating, overdrinking, or another cause)","cn":"恶心、想吐（因吃多或喝多等原因而觉得恶心、想吐的样子）","ne":"वाकवाकी"},
 {"kanji":"栄養","kana":"えいよう","eng":"nutrition","cn":"营养","ne":"पौष्टिकता"},
 {"kanji":"肩","kana":"かた","eng":"shoulder","cn":"肩膀","ne":"काँध"},
 {"kanji":"首","kana":"くび","eng":"neck","cn":"头颈","ne":"घाँटी"},
 {"kanji":"カロリー","kana":"","eng":"calorie","cn":"热量","ne":"क्‍यालोरि"},
 {"kanji":"健康","kana":"けんこう","eng":"health, fitness","cn":"健康","ne":"स्वास्थ्य"},
 {"kanji":"この頃","kana":"このごろ","eng":"these days, nowadays","cn":"近来、最近","ne":"आज भोलि"},
 {"kanji":"ジューサー","kana":"","eng":"juicer","cn":"果汁机","ne":"जुस बनाउने मेशिन"},
 {"kanji":"ショウガ","kana":"","eng":"ginger","cn":"生姜","ne":"अदुवा"},
 {"kanji":"ストレス","kana":"","eng":"stress","cn":"精神压力","ne":"स्‍ट्रेस"},
 {"kanji":"体脂肪","kana":"たいしぼう","eng":"body fat","cn":"体脂","ne":"शरीरको बोसो"},
 {"kanji":"ネックストレッチャー","kana":"","eng":"neck brace, neck collar","cn":"颈部伸展器","ne":"घाँटी तनाउने"},
 {"kanji":"バランス","kana":"","eng":"balance","cn":"平衡","ne":"ब्‍यालेन्स/संतुलन"},
 {"kanji":"ビタミンC","kana":"","eng":"vitamin C","cn":"维生素C","ne":"भिटामीन C"},
 {"kanji":"ヘルスケア","kana":"","eng":"healthcare, fitness","cn":"医疗保健","ne":"स्वास्थ्य हेरचाह"},
 {"kanji":"マッサージ器","kana":"","eng":"massage machine","cn":"按摩器","ne":"मशाज मेशिन"},
 {"kanji":"～計（例：温度計）","kana":"～けい（れい：おんどけい）","eng":"～ meter (example: thermometer)","cn":"……计（例：温度计）","ne":"～मिटर (जस्‍टै: थर्मोमिटर)"},
 {"kanji":"～不足（例：運動不足）","kana":"～ぶそく（れい：うんどうぶそく）","eng":"deficiency in ～, not enough ～ (example: not enough exercise)","cn":"……不足（例：运动不足）","ne":"～को कमी (जस्तो: खेलकुदको कमी)"},
 {"kanji":"～率（例：出席率）","kana":"～りつ（れい：しゅっせきりつ）","eng":"～ rate, ～ ratio, ～ percentage (example: attendance rate)","cn":"……率（例：出席率）","ne":"～दर (जस्‍टै: उपस्थिति दर)"},
 {"kanji":"動かす","kana":"うごかす","eng":"move, set in motion","cn":"动、活动","ne":"चलाउनु"},
 {"kanji":"こる","kana":"こる","eng":"become stiff","cn":"酸痛","ne":"साह्रो हुनु"},
 {"kanji":"たまる","kana":"たまる","eng":"build up","cn":"积聚","ne":"थुप्रिनु"},
 {"kanji":"取る","kana":"とる","eng":"break free from, relieve","cn":"去除","ne":"लिनु/मेट्नु"},
 {"kanji":"疲れを取る","kana":"つかれをとる","eng":"relieve one’s fatigue","cn":"去除疲劳","ne":"थकाइ मेट्नु"},
 {"kanji":"眠る","kana":"ねむる","eng":"sleep","cn":"睡觉","ne":"निदाउनु"},
 {"kanji":"測る","kana":"はかる","eng":"measure","cn":"测量","ne":"नाप्‍छु"},
 {"kanji":"太る","kana":"ふとる","eng":"gain weight, get fat","cn":"胖","ne":"मोटाउनु"},
 {"kanji":"痩せる","kana":"やせる","eng":"lose weight, become thin","cn":"瘦","ne":"दुब्‍लाउनु"},
 {"kanji":"冷える","kana":"ひえる","eng":"chill, get cold","cn":"凉","ne":"चिसो हुनु"},
 {"kanji":"計算・する","kana":"けいさん・する","eng":"calculate","cn":"计算","ne":"गणना/हिसाब गर्नु"},
 {"kanji":"ダイエット・する","kana":"","eng":"diet","cn":"减肥","ne":"डायट गर्नु"},
 {"kanji":"マッサージ・する","kana":"","eng":"massage","cn":"按摩","ne":"मशाज गर्नु"},
 {"kanji":"キャラクター","kana":"","eng":"(fictional) character, personality","cn":"角色、性格","ne":"क्यारेक्टर"},
 {"kanji":"グレープフルーツ","kana":"","eng":"grapefruit","cn":"西柚","ne":"ग्‍रेपफ्रुट"},
 {"kanji":"二日酔い","kana":"ふつかよ","eng":"hangover","cn":"醉到第二天","ne":"भोलिपल्टसम्म रक्सि लागिरहेको अवस्‍था"},
 {"kanji":"管理・する","kana":"かんり・する","eng":"manage, administer","cn":"管理","ne":"नियन्त्रण गर्नु"},
 {"kanji":"成長・する","kana":"せいちょう・する","eng":"grow, develop","cn":"成长","ne":"हुर्‍कनु"},
 {"kanji":"気にする","kana":"きにする","eng":"feel uneasy, be worried (about)","cn":"在意、介意","ne":"ध्यान गर्नु"},
 {"kanji":"気をつける","kana":"きをつける","eng":"be careful","cn":"当心、留神","ne":"ध्यान दिनु"},
 {"kanji":"ほとんど","kana":"ほとんど","eng":"hardly","cn":"几乎","ne":"प्रायजसो"},
 {"kanji":"～とも","kana":"～とも","eng":"both","cn":"……共、……都","ne":"～साथै"},
],
13: [
 {"kanji":"偉い","kana":"えらい","eng":"great, excellent, well done","cn":"了不起","ne":"एकदम/असल"},
 {"kanji":"自然","kana":"しぜん","eng":"nature","cn":"大自然","ne":"प्रकृति"},
 {"kanji":"釣る","kana":"つる","eng":"fish","cn":"钓鱼","ne":"माछा मार्‍नु"},
 {"kanji":"自由（な）","kana":"じゆう（な）","eng":"free, at will","cn":"自由（的）","ne":"स्वतन्त्रता"},
 {"kanji":"必ず","kana":"かならず","eng":"by all means, certainly","cn":"一定、必须","ne":"अवश्य पनि"},
 {"kanji":"手に入れる","kana":"てにいれる","eng":"obtain, acquire","cn":"拿到手","ne":"हात पार्‍नु"},
 {"kanji":"やっぱり","kana":"やっぱり","eng":"after all","cn":"还是、毕竟","ne":"नभन्दै"},
 {"kanji":"不利（な）","kana":"ふり（な）","eng":"disadvantageous","cn":"不利（的）","ne":"बेफाइदाजनक"},
 {"kanji":"遅くまで","kana":"おそくまで","eng":"(doing something) until late","cn":"直到很晚","ne":"ढिलो सम्म"},
 {"kanji":"男の子","kana":"おとこのこ","eng":"boy","cn":"男孩","ne":"केटा बच्चा"},
 {"kanji":"親","kana":"おや","eng":"parent","cn":"家长、父母","ne":"बुबाआमा"},
 {"kanji":"父親","kana":"ちちおや","eng":"father","cn":"父亲","ne":"बुबा"},
 {"kanji":"母親","kana":"ははおや","eng":"mother","cn":"母亲","ne":"आमा"},
 {"kanji":"家事","kana":"かじ","eng":"housework","cn":"家务","ne":"घरेलु कामकाज"},
 {"kanji":"ゲームセンター","kana":"","eng":"game center","cn":"电玩中心","ne":"गेम सेन्टर"},
 {"kanji":"コーチ","kana":"","eng":"coach","cn":"教练","ne":"कोच"},
 {"kanji":"習い事","kana":"ならいごと","eng":"lessons (violin lessons, ballet lessons, etc.)","cn":"练习、学习","ne":"पैसा तिरेर सिक्‍ने कुरा"},
 {"kanji":"頃","kana":"ころ","eng":"when I was ～","cn":"时候","ne":"बेला"},
 {"kanji":"塾","kana":"じゅく","eng":"after-school cram school","cn":"补习班","ne":"ट्युशन स्‍कुल"},
 {"kanji":"数学","kana":"すうがく","eng":"mathematics, math","cn":"数学","ne":"गणित शास्त्र"},
 {"kanji":"～キロ","kana":"～キロ","eng":"～ kilometers, ～ kilograms","cn":"……公里","ne":"～किलो"},
 {"kanji":"～ずつ（例：20個ずつ）","kana":"～ずつ（れい：にじゅっこずつ）","eng":"～ each, ～ per (example: 20 each)","cn":"各……、每……（例：各20个）","ne":"～प्रत्येक (जस्‍टै: २० वटामा प्रत्येक)"},
 {"kanji":"騒ぐ","kana":"さわぐ","eng":"be noisy, act up","cn":"吵闹","ne":"होहल्‍ला गर्नु"},
 {"kanji":"世話・する","kana":"せわ・する","eng":"take care of","cn":"照顾","ne":"सत्कार/सेवा गर्नु"},
 {"kanji":"海外","kana":"かいがい","eng":"overseas","cn":"海外、国外","ne":"विदेश"},
 {"kanji":"教育","kana":"きょういく","eng":"education","cn":"教育","ne":"शिक्षा"},
 {"kanji":"曲","kana":"きょく","eng":"song track","cn":"曲子","ne":"गाना"},
 {"kanji":"化粧品","kana":"けしょうひん","eng":"cosmetics","cn":"化妆品","ne":"मेकअपको सामान"},
 {"kanji":"手伝い","kana":"てつだい","eng":"help, assistance, assistant","cn":"帮助","ne":"मद्दत"},
 {"kanji":"～会（例：発表会）","kana":"～かい（れい：はっぴょうかい）","eng":"～ meet(ing), ～ session, ～ presentation (used for events like recitals, school concerts, etc.)","cn":"……会（例：发布会）","ne":"～सभा (जस्‍टै: प्रस्तुतिका सभा)"},
 {"kanji":"叱る","kana":"しかる","eng":"scold","cn":"责备、斥责","ne":"गाली गर्नु"},
 {"kanji":"泣く","kana":"なく","eng":"cry","cn":"哭","ne":"रुनु"},
 {"kanji":"残す","kana":"のこす","eng":"leave, save","cn":"留下","ne":"बाँकी छोड्नु"},
 {"kanji":"やる","kana":"やる","eng":"do","cn":"做","ne":"गर्नु"},
 {"kanji":"宿題をやる","kana":"しゅくだいをやる","eng":"do my homework","cn":"做作业","ne":"गृहकार्‍य गर्नु"},
 {"kanji":"褒める","kana":"ほめる","eng":"praise","cn":"表扬","ne":"प्रशंसा गर्नु"},
 {"kanji":"やめる","kana":"やめる","eng":"quit, stop, give up","cn":"停止、放弃","ne":"छोड्नु"},
 {"kanji":"発表・する","kana":"はっぴょう・する","eng":"announce","cn":"发表","ne":"प्रस्‍तुत गर्नु"},
 {"kanji":"厳しい","kana":"きびしい","eng":"strict, severe","cn":"严格、严厉","ne":"कडा स्वभावको"},
 {"kanji":"嫌（な）","kana":"いや（な）","eng":"disagreeable, unpleasant","cn":"不喜欢（的）、不乐意（的）","ne":"मन नपर्ने"},
 {"kanji":"熱心（な）","kana":"ねっしん（な）","eng":"eager, enthusiastic, devoted","cn":"热心（的）","ne":"जोशका साथ"},
 {"kanji":"何でも","kana":"なんでも","eng":"anything","cn":"什么都","ne":"जे पनि"},
 {"kanji":"おもちゃ","kana":"おもちゃ","eng":"toy","cn":"玩具","ne":"खेलौना"},
 {"kanji":"祖母","kana":"そぼ","eng":"grandmother","cn":"祖母","ne":"हजुरआमा"},
 {"kanji":"僕","kana":"ぼく","eng":"I, me (informal, used primarily by young men)","cn":"我","ne":"म"},
 {"kanji":"役に立つ","kana":"やくにたつ","eng":"be useful","cn":"有用、有帮助","ne":"काम लाग्‍ने"},
 {"kanji":"ちゃんと","kana":"ちゃんと","eng":"properly","cn":"切实、确实","ne":"राम्रोसँग"},
 {"kanji":"仕方がない","kana":"しかたがない","eng":"no choice, have no alternative","cn":"没有办法、无奈","ne":"कुनै उपाय छैन"},
],
14: [
 {"kanji":"おもちゃ","kana":"おもちゃ","eng":"toy","cn":"玩具","ne":"खेलौना"},
 {"kanji":"作品","kana":"さくひん","eng":"work (picture/painting, etc.)","cn":"作品","ne":"रचना"},
 {"kanji":"女の子","kana":"おんなのこ","eng":"girl","cn":"女孩子","ne":"केटी"},
 {"kanji":"数","kana":"かず","eng":"number","cn":"数字","ne":"सङ्‍ख्या"},
 {"kanji":"奨学金","kana":"しょうがくきん","eng":"scholarship","cn":"奖学金","ne":"छात्रवृत्ति"},
 {"kanji":"（お）金持ち","kana":"（お）かねもち","eng":"rich person","cn":"有钱人","ne":"धनि"},
 {"kanji":"漫画家","kana":"まんがか","eng":"cartoonist","cn":"漫画家","ne":"कार्‍टटुनिस्ट"},
 {"kanji":"カボチャ","kana":"","eng":"pumpkin","cn":"南瓜","ne":"फर्‍सि"},
 {"kanji":"～部","kana":"～ぶ","eng":"～ department, ～ section","cn":"……部","ne":"～क्लब/टिम"},
 {"kanji":"空手","kana":"からて","eng":"karate","cn":"空手道","ne":"कराते"},
 {"kanji":"活動・する","kana":"かつどう・する","eng":"be active, operate","cn":"活动","ne":"गतिविधि गर्नु"},
 {"kanji":"ギョーザ","kana":"","eng":"dumpling, potstickers","cn":"饺子","ne":"ग्‍योजा(चिनियाँ म:म:)"},
 {"kanji":"支援・する","kana":"しえん・する","eng":"support","cn":"援助","ne":"सहयोग गर्नु"},
 {"kanji":"行事","kana":"ぎょうじ","eng":"event, occasion","cn":"仪式、活动","ne":"उत्सवहरू"},
 {"kanji":"ヒット・する","kana":"","eng":"be a hit","cn":"大受欢迎","ne":"हिट हुनु/एकदम चल्नु"},
 {"kanji":"大みそか","kana":"おおみそか","eng":"new year’s eve","cn":"除夕","ne":"वर्‍षको अन्तिम दिन"},
 {"kanji":"放送・する","kana":"ほうそう・する","eng":"broadcast, air","cn":"播放、传播","ne":"प्रसारण गर्नु"},
 {"kanji":"お盆","kana":"おぼん","eng":"obon festival","cn":"盂兰盆节","ne":"ओबोन पर्‍व"},
 {"kanji":"連載・する","kana":"れんさい・する","eng":"appear serially (in a publication)","cn":"连载","ne":"नियमित रूपमा प्रकाशन गर्नु"},
 {"kanji":"素晴らしい","kana":"すばらしい","eng":"magnificent, incredible","cn":"精彩的、出色的、好","ne":"अति उत्तम"},
 {"kanji":"敬老の日","kana":"けいろうのひ","eng":"Respect-for-the-Aged Day (a national holiday held on the 3rd month of September for revering the elderly and wishing them a long life)","cn":"敬老日（国民节日之一，定于9月份的第3个星期一。是敬爱老人，祝愿其长寿的日子）","ne":"पौढ दिवस"},
 {"kanji":"メジャー（な）","kana":"","eng":"major","cn":"主流（的）","ne":"मेजर"},
 {"kanji":"七五三","kana":"しちごさん","eng":"Seven-Five-Three Festival (festival celebrating the growth of children for boys when they are three and five years old and for girls when they are three and seven years old)","cn":"七五三（男孩在三岁和五岁时、女孩在三岁和七岁时举行的祝福孩子成长的仪式）","ne":"सिचिगोसान (सात, पाँच र तिन वर्‍षका बालकको उत्सव)"},
 {"kanji":"遊び","kana":"あそび","eng":"game, play","cn":"玩","ne":"खेल/रमझम"},
 {"kanji":"ウナギ","kana":"","eng":"eel","cn":"鳗鱼","ne":"उनागि माछा"},
 {"kanji":"大勢","kana":"おおぜい","eng":"crowd, in large numbers","cn":"众多、大批","ne":"थुप्रै मानिसहरू"},
 {"kanji":"おせち料理","kana":"おせちりょうり","eng":"traditional New Year’s food (primarily food eaten to celebrate the New Year)","cn":"日本年菜、日本年饭（主要指在新年时吃的菜）","ne":"ओसेची परिकार(जापानी नयाँ वर्‍षमा खाने विशेष परिकार)"},
 {"kanji":"（お）正月","kana":"（お）しょうがつ","eng":"New Year’s holidays","cn":"新年、正月","ne":"नयाँ वर्‍ष"},
 {"kanji":"招き猫","kana":"まねきねこ","eng":"Welcoming cat (statue of a cat with its front paw beckoning customers that is used as a decoration for storefronts and other locations)","cn":"招财猫（伸出前脚招揽行人的猫型摆设。装饰在商店等处用来招揽顾客）","ne":"मानेकि नेको(पसलमा राखिने एक किसिमको बिरालोको मूर्ति)"},
 {"kanji":"成人の日","kana":"せいじんのひ","eng":"Coming of Age Day (a national holiday held on the 2nd Monday in January to congratulate those who have reached legal adulthood)","cn":"成人节","ne":"वालिग दिवस"},
 {"kanji":"豆","kana":"まめ","eng":"bean","cn":"豆子","ne":"गेडागुडी"},
 {"kanji":"節分","kana":"せつぶん","eng":"Traditional end of winter (held the day before the traditional beginning of spring (around February 3). On the evening of this day, beans are thrown around the house to ward off evil)","cn":"节分（是指立春的前一天（2月3日左右）。在这天夜里，有撒豆驱鬼、驱赶邪气的习俗）","ne":"सेचुबुन पर्‍व"},
 {"kanji":"ミカン","kana":"","eng":"tangerine","cn":"桔子","ne":"सुन्तला"},
 {"kanji":"焼き鳥","kana":"やきとり","eng":"yakitori (skewered grilled chicken)","cn":"烤鸡（鸟）肉串","ne":"कुखुराको मासुको सेकुवा"},
 {"kanji":"ユズ","kana":"","eng":"yuzu (Chinese lemon)","cn":"香橙","ne":"चिनियाँ कागती"},
 {"kanji":"夢","kana":"ゆめ","eng":"dream (during sleep)","cn":"梦、梦想","ne":"सपना"},
 {"kanji":"昨日、悪い夢を見た","kana":"きのう、わるいゆめをみた","eng":"“I had a bad dream yesterday.”","cn":"昨天（我）做了噩梦。","ne":"हिजो मैले नराम्रो सपना देखेँ।"},
 {"kanji":"冬至","kana":"とうじ","eng":"winter solstice","cn":"冬至","ne":"मकर सङ्‍्क्रान्‍ति"},
 {"kanji":"ランドセル","kana":"","eng":"satchel, school backpack for elementary school","cn":"双肩书包","ne":"स्‍कुल ब्‍याग"},
 {"kanji":"土用の丑の日","kana":"どようのうしのひ","eng":"Midsummer Day of the Ox","cn":"暑伏丑日","ne":"दोयोनो उसिनो हि"},
 {"kanji":"～県（例：長崎県）","kana":"～けん（れい：ながさきけん）","eng":"～ prefecture (example: Nagasaki prefecture)","cn":"……县（例：长崎县）","ne":"अञ्चल (जस्तो: नागासाकि अञ्चल)"},
 {"kanji":"祈る","kana":"いのる","eng":"pray","cn":"祈祷、祝愿","ne":"प्रार्थना गर्नु"},
 {"kanji":"ひなまつり","kana":"ひなまつり","eng":"Doll Festival (festival held on March 3 for celebrating the growth of young girls)","cn":"女儿节（在3月3日举行的祝福女孩子成长的仪式）","ne":"हिनामाचुरि पर्‍व"},
 {"kanji":"祝う","kana":"いわう","eng":"celebrate, mark an occasion of, congratulate on","cn":"祝贺","ne":"मनाउनु"},
 {"kanji":"ごちそう","kana":"ごちそう","eng":"big meal, feast","cn":"丰盛的饭菜、好吃的东西","ne":"मीठा मीठा परिकार"},
 {"kanji":"新年","kana":"しんねん","eng":"New Year’s Day","cn":"新年","ne":"नयाँ साल"},
 {"kanji":"踊る","kana":"おどる","eng":"dance","cn":"跳舞","ne":"नाच्‍छु"},
 {"kanji":"将棋","kana":"しょうぎ","eng":"shogi (Japanese chess)","cn":"日本象棋","ne":"स्‍योगि खेल"},
 {"kanji":"飾る","kana":"かざる","eng":"decorate, put up a decoration","cn":"装饰、装点","ne":"सजाउनु"},
 {"kanji":"スイカ","kana":"","eng":"watermelon","cn":"西瓜","ne":"खरभुजा"},
 {"kanji":"包む","kana":"つつむ","eng":"wrap up, roll up","cn":"包、包裹","ne":"ढाक्‍छु/छोप्‍छु"},
 {"kanji":"（お）赤飯","kana":"（お）せきはん","eng":"festive red rice","cn":"红豆饭","ne":"(ओ)सेकिहान/रातो भात (शुभ अवसरमा खाइने)"},
 {"kanji":"お祝い・する","kana":"おいわい・する","eng":"celebrate","cn":"庆贺、祝贺","ne":"उपलक्ष्य मा समारोह गर्नु"},
 {"kanji":"先祖","kana":"せんぞ","eng":"ancestor","cn":"祖先","ne":"पूर्खाहरू"},
 {"kanji":"感謝・する","kana":"かんしゃ・する","eng":"thank, express appreciation","cn":"感谢","ne":"आभारी हुनु"},
 {"kanji":"山車","kana":"だし","eng":"parade float","cn":"彩车","ne":"रथ"},
 {"kanji":"チェス","kana":"","eng":"chess","cn":"国际象棋","ne":"चेस"},
 {"kanji":"成長・する","kana":"せいちょう・する","eng":"grow, develop","cn":"成长","ne":"हुर्‍कनु"},
 {"kanji":"テコンドー","kana":"","eng":"tae kwon do","cn":"跆拳道","ne":"ताइक्ववांडो"},
 {"kanji":"長生き・する","kana":"ながいき・する","eng":"live a long life","cn":"长寿","ne":"चिरन्जिवी हुनु"},
 {"kanji":"年","kana":"とし","eng":"age, year","cn":"岁数、年龄","ne":"साल"},
 {"kanji":"夏バテ・する","kana":"なつバテ・する","eng":"suffer from the summer heat","cn":"夏日倦怠","ne":"धेरै गर्मीको कारणले लखतरान हुनु"},
 {"kanji":"新しい年","kana":"あたらしいとし","eng":"a new year, the coming year","cn":"新的一年","ne":"नयाँ वर्‍ष"},
 {"kanji":"特別（な）","kana":"とくべつ（な）","eng":"Special","cn":"特别（的）","ne":"विशेष"},
 {"kanji":"パクさんの年","kana":"パクさんのとし","eng":"Pak’s age","cn":"朴先生（女士）的年龄","ne":"पार्‍कजीको उमेर"},
 {"kanji":"布","kana":"ぬの","eng":"fabric","cn":"布","ne":"कपडा"},
 {"kanji":"イヤホン","kana":"","eng":"earphones","cn":"耳机","ne":"एअरफोन"},
 {"kanji":"年賀状","kana":"ねんがじょう","eng":"new year’s greeting card","cn":"贺年卡","ne":"नयाँ वर्‍षको कार्‍ड"},
 {"kanji":"置物","kana":"おきもの","eng":"ornament","cn":"摆设","ne":"सजाएर राख्‍ने सामान"},
 {"kanji":"火事","kana":"かじ","eng":"fire","cn":"火灾","ne":"आगलागी"},
 {"kanji":"カメ","kana":"","eng":"turtle, tortoise","cn":"乌龟","ne":"कछुवा"},
 {"kanji":"はがき","kana":"はがき","eng":"postcard","cn":"明信片","ne":"पोस्ट कार्‍ड"},
 {"kanji":"風呂敷","kana":"ふろしき","eng":"cloth for wrapping things","cn":"包袱布","ne":"फुरोसिकि रुमाल"},
 {"kanji":"菊","kana":"きく","eng":"chrysanthemum","cn":"菊花","ne":"गोदावरी फूल"},
 {"kanji":"くし","kana":"くし","eng":"hair comb","cn":"梳子","ne":"काइँयो"},
 {"kanji":"５円玉","kana":"ごえんだま","eng":"five yen coin","cn":"5日元硬币","ne":"५ येनको डबल"},
 {"kanji":"食器","kana":"しょっき","eng":"dishes, tableware","cn":"餐具","ne":"थाल कचौरा"},
 {"kanji":"シンボル","kana":"","eng":"symbol","cn":"象征","ne":"सिम्बल/प्रतीक"},
 {"kanji":"ストーブ","kana":"","eng":"stove, space heater","cn":"炉子","ne":"हीटर"},
 {"kanji":"（お）葬式","kana":"（お）そうしき","eng":"funeral ceremony","cn":"葬礼","ne":"किरिया कर्‍म"},
 {"kanji":"涙","kana":"なみだ","eng":"tears","cn":"眼泪","ne":"आँशु"},
 {"kanji":"ハンカチ","kana":"","eng":"handkerchief","cn":"手帕","ne":"रुमाल"},
 {"kanji":"日傘","kana":"ひがさ","eng":"parasol, sunshade","cn":"遮阳伞","ne":"घाममा ओढ्ने छाता"},
 {"kanji":"（お）見舞い","kana":"（お）みまい","eng":"visit a sick person","cn":"探望","ne":"बिरामीलाई भेट्न जाने"},
 {"kanji":"みんな","kana":"みんな","eng":"everyone","cn":"大家","ne":"सबैजना"},
 {"kanji":"ライター","kana":"","eng":"lighter","cn":"打火机","ne":"लाइटर"},
 {"kanji":"～祝い（例：結婚祝い）","kana":"～いわい（れい：けっこんいわい）","eng":"in celebration of ～ (example: wedding present)","cn":"……贺礼（例：结婚贺礼）","ne":"～मनाउने (जस्तो: विवाहको उपहार)"},
 {"kanji":"贈る","kana":"おくる","eng":"give a gift","cn":"赠送","ne":"पठाउनु/उपहार दिनु"},
 {"kanji":"増える","kana":"ふえる","eng":"increase, grow in number","cn":"增加","ne":"वृद्धि हुनु"},
 {"kanji":"発音・する","kana":"はつおん・する","eng":"pronounce","cn":"发音","ne":"उच्चारण गर्नु"},
 {"kanji":"連想・する","kana":"れんそう・する","eng":"make an association of ideas","cn":"联想","ne":"झझल्को हुनु"},
 {"kanji":"恥ずかしい","kana":"はずかしい","eng":"embarrassing","cn":"害羞、不好意思","ne":"लाजलाग्‍छो"},
 {"kanji":"鬼","kana":"おに","eng":"demon, devil","cn":"鬼","ne":"राक्षस"},
 {"kanji":"提灯","kana":"ちょうちん","eng":"paper lantern","cn":"灯笼","ne":"लालटिन"},
 {"kanji":"ハロウィン","kana":"","eng":"Halloween","cn":"万圣节","ne":"हलोविन"},
 {"kanji":"そういう","kana":"そういう","eng":"that kind of ～, like that, such","cn":"那种、那样的","ne":"त्यस्‍तो भनिने"},
],
15: [
 {"kanji":"テーマ","kana":"","eng":"theme, topic, subject (from the German word thema)","cn":"主题","ne":"मुख्‍य बुँदा / कुरा"},
 {"kanji":"自信","kana":"じしん","eng":"confidence","cn":"自信","ne":"आत्मविश्वास"},
 {"kanji":"知り合い","kana":"しりあい","eng":"acquaintance","cn":"相识、熟人","ne":"चिनेको मान्‍छे"},
 {"kanji":"貿易","kana":"ぼうえき","eng":"foreign trade","cn":"贸易","ne":"ट्‍्रेड"},
 {"kanji":"大成功","kana":"だいせいこう","eng":"great success","cn":"非常成功","ne":"एकदम सफल"},
 {"kanji":"問題","kana":"もんだい","eng":"problem, issue","cn":"问题","ne":"समस्‍या"},
 {"kanji":"取り組む","kana":"とりくむ","eng":"deal with, engage in, work on","cn":"全力处理","ne":"मिहिनेत गर्नु"},
 {"kanji":"積極的（な）","kana":"せっきょくてき（な）","eng":"proactive, positive","cn":"积极的","ne":"सक्रियताका साथ"},
 {"kanji":"～化（例：温暖化）","kana":"～か（れい：おんだんか）","eng":"change into ～ (example: global warming)","cn":"……化（例：温暖化）","ne":"～करण (जस्तो: ऊष्‍मीकरण)"},
 {"kanji":"大雨","kana":"おおあめ","eng":"heavy rain","cn":"大雨","ne":"ठूलो वर्षा"},
 {"kanji":"英会話","kana":"えいかいわ","eng":"English conversation","cn":"英语会话","ne":"अंग्‍रेजीमा कुराकानी"},
 {"kanji":"回数","kana":"かいすう","eng":"number of times","cn":"次数","ne":"पटक"},
 {"kanji":"グラフ","kana":"","eng":"graph","cn":"图表","ne":"ग्‍राफ"},
 {"kanji":"グループ","kana":"","eng":"group","cn":"组","ne":"समूह"},
 {"kanji":"原因","kana":"げんいん","eng":"cause","cn":"原因","ne":"कारण"},
 {"kanji":"事件","kana":"じけん","eng":"incident, case, event","cn":"事件、案件","ne":"घटना"},
 {"kanji":"事情","kana":"じじょう","eng":"situation, circumstances, conditions","cn":"情况、状况","ne":"परिस्थिति/समस्‍या"},
 {"kanji":"食料品","kana":"しょくりょうひん","eng":"food items","cn":"食品","ne":"खाद्य पदार्‍थ"},
 {"kanji":"アンケート・する","kana":"","eng":"take a survey","cn":"进行问卷调查","ne":"लिखित अन्तरवार्ता गर्नु"},
 {"kanji":"女性","kana":"じょせい","eng":"female","cn":"女性","ne":"महिला/आइमाई"},
 {"kanji":"男性","kana":"だんせい","eng":"male","cn":"男性","ne":"पुरुष/लोग्‍नेमान्‍छे"},
 {"kanji":"地球","kana":"ちきゅう","eng":"the Earth","cn":"地球","ne":"पृथ्‍वी"},
 {"kanji":"増加・する","kana":"ぞうか・する","eng":"increase","cn":"增加","ne":"वृद्धि हुनु"},
 {"kanji":"輸入・する","kana":"ゆにゅう・する","eng":"import","cn":"进口","ne":"आयात गर्नु"},
 {"kanji":"来日・する","kana":"らいにち・する","eng":"visit Japan","cn":"来日本","ne":"जापानमा आउनु"},
 {"kanji":"流行・する","kana":"りゅうこう・する","eng":"become fashionable, popular","cn":"流行","ne":"चलनमा आउनु"},
 {"kanji":"気になる","kana":"きになる","eng":"worry about, care about, be interested in","cn":"担心、介意","ne":"मनमा लाग्‍छु"},
 {"kanji":"洋服","kana":"ようふく","eng":"(Western-style) clothing","cn":"服装、衣服","ne":"लुगा"},
 {"kanji":"レコード","kana":"","eng":"record","cn":"唱片","ne":"रेकर्‍ड"},
 {"kanji":"～倍","kana":"～ばい","eng":"by ～ times","cn":"……倍","ne":"～गुणा"},
 {"kanji":"飼う","kana":"かう","eng":"raise (a pet or other animal)","cn":"饲养","ne":"पाल्नु(जनावर आदि)"},
 {"kanji":"下がる","kana":"さがる","eng":"fall, drop","cn":"下降","ne":"घट्नु"},
 {"kanji":"値段が下がる","kana":"ねだんがさがる","eng":"the price drops","cn":"价格下降","ne":"मूल्य घट्नु"},
 {"kanji":"咲く","kana":"さく","eng":"blossom","cn":"（花）开","ne":"फुल्नु"},
 {"kanji":"過ごす","kana":"すごす","eng":"spend time","cn":"度过","ne":"बिताउनु"},
 {"kanji":"植える","kana":"うえる","eng":"to plant","cn":"栽、种","ne":"रोप्‍छु"},
 {"kanji":"比べる","kana":"くらべる","eng":"compare","cn":"比较","ne":"तुलना गर्नु"},
 {"kanji":"お願い・する","kana":"おねがい・する","eng":"ask, beg (when politely requesting someone to do something for you)","cn":"拜托、劳驾","ne":"विन्‍ती गर्नु"},
 {"kanji":"僕","kana":"ぼく","eng":"I, me (informal, used primarily by young men)","cn":"我","ne":"म"},
 {"kanji":"前","kana":"まえ","eng":"before","cn":"前","ne":"अघि"},
 {"kanji":"気楽（な）","kana":"きらく（な）","eng":"carefree","cn":"轻松、安闲","ne":"निश्चिन्त"},
 {"kanji":"不安（な）","kana":"ふあん（な）","eng":"unease","cn":"不安、担心","ne":"अशान्त खालको"},
 {"kanji":"約～","kana":"やく～","eng":"about, approximately","cn":"大约","ne":"लगभग/करिब"},
 {"kanji":"汚い","kana":"きたない","eng":"dirty","cn":"脏","ne":"फोहोर"},
 {"kanji":"温暖（な）","kana":"おんだん（な）","eng":"warm","cn":"温暖的","ne":"न्‍यानो"},
 {"kanji":"直接","kana":"ちょくせつ","eng":"direct","cn":"直接","ne":"प्रत्यक्ष"},
 {"kanji":"ほとんど","kana":"ほとんど","eng":"hardly","cn":"几乎","ne":"प्रायजसो"},
 {"kanji":"インフルエンザ","kana":"","eng":"flu, influenza","cn":"流感","ne":"इन्फ्‍लुयन्जा"},
 {"kanji":"円高","kana":"えんだか","eng":"strong yen, yen appreciation","cn":"日元升值","ne":"येनको मूल्यमा वृद्धि"},
 {"kanji":"円安","kana":"えんやす","eng":"weak yen, yen depreciation","cn":"日元贬值","ne":"येनको मूल्यमा कमी"},
 {"kanji":"気温","kana":"きおん","eng":"air temperature","cn":"气温","ne":"तापक्रम"},
 {"kanji":"立入禁止","kana":"たちいりきんし","eng":"entry prohibited","cn":"禁止入内","ne":"प्रवेश निषेध"},
 {"kanji":"南極","kana":"なんきょく","eng":"south pole","cn":"南极","ne":"दक्षिणी ध्‍रुव"},
 {"kanji":"北極","kana":"ほっきょく","eng":"north pole","cn":"北极","ne":"उत्तरी ध्‍रुव"},
 {"kanji":"ポスター","kana":"","eng":"poster","cn":"海报","ne":"पोस्टर"},
 {"kanji":"進む","kana":"すすむ","eng":"move forward, advance","cn":"进展","ne":"अघि बढ्नु"},
 {"kanji":"研究が進む","kana":"けんきゅうがすすむ","eng":"“The research moves forward.”","cn":"研究有进展。","ne":"अनुसन्‍धान अगाडि बढ्नु"},
 {"kanji":"減る","kana":"へる","eng":"decrease, reduce in number","cn":"减少","ne":"ह्‍रास हुनु"},
 {"kanji":"溶ける","kana":"とける","eng":"melt","cn":"溶化","ne":"पग्लनु"},
 {"kanji":"欠席・する","kana":"けっせき・する","eng":"be absent, not attend","cn":"缺席","ne":"अनुपस्थित हुनु"},
 {"kanji":"輸出・する","kana":"ゆしゅつ・する","eng":"export","cn":"出口","ne":"निर्‍यात गर्नु"},
 {"kanji":"危険（な）","kana":"きけん（な）","eng":"dangerous, hazardous","cn":"危险（的）","ne":"खतरनाक"},
 {"kanji":"大変","kana":"たいへん","eng":"very","cn":"很、非常","ne":"एकदमै"},
 {"kanji":"どんどん","kana":"どんどん","eng":"more and more","cn":"接二连三","ne":"झनझन"},
 {"kanji":"しかし","kana":"しかし","eng":"however, but","cn":"但是","ne":"तर"},
 {"kanji":"～によると","kana":"～によると","eng":"according to ～","cn":"根据……","ne":"~का अनुसार"},
 {"kanji":"行き先","kana":"いきさき","eng":"destination","cn":"目的地、去向","ne":"गन्तव्य"},
 {"kanji":"結果","kana":"けっか","eng":"results","cn":"结果","ne":"परिणाम"},
 {"kanji":"サイト","kana":"","eng":"website","cn":"站点","ne":"वेब साइट"},
 {"kanji":"全体","kana":"ぜんたい","eng":"overall","cn":"整体、全体","ne":"सम्पूर्‍ण भाग"},
],
}
